raccoon: org.msrg.raccoon.SourceCodedBatch.code
code()
CodedPiece org.msrg.raccoon.SourceCodedBatch.code ()
Implements org.msrg.raccoon.ICodedBatch.
Definition at line 24 of file SourceCodedBatch.java.
References org.msrg.raccoon.CodedBatch._bm, and org.msrg.raccoon.CodedPiece.makeCodedPiece().
Referenced by org.msrg.raccoon.CodedBatchTest.testReceivedCodedBatch(), and org.msrg.raccoon.SlicedCodedBatchTest.testReceivedCodedBatch().
{
         return CodedPiece.makeCodedPiece(_bm);
     }