raccoon: org.msrg.raccoon.CodedPiece.makeCodedPiece
static CodedPiece org.msrg.raccoon.CodedPiece.makeCodedPiece (BulkMatrix bm) static
Definition at line 21 of file CodedPiece.java.
References org.msrg.raccoon.matrix.bulk.BulkMatrix._rows, and org.msrg.raccoon.CodedPiece.CodedPiece().
Referenced by org.msrg.raccoon.SourceCodedBatch.code(), org.msrg.raccoon.CodedPieceTest.setUp(), and org.msrg.raccoon.ReceivedCodedBatchTest.ttestEncodingDecodingReceivedCodedBatch().
{
         CodedCoefficients cc = new CodedCoefficients(bm._rows);
         return new CodedPiece(cc, bm);
     }