raccoon: org.msrg.raccoon.engine.task.sequential.EncodingReceivedCodedBatch_SequentialCodingTask.runStagePrivately
runStagePrivately()
synchronized void org.msrg.raccoon.engine.task.sequential.EncodingReceivedCodedBatch_SequentialCodingTask.runStagePrivately () protected
Definition at line 39 of file EncodingReceivedCodedBatch_SequentialCodingTask.java.
References org.msrg.raccoon.CodedPiece._cc, org.msrg.raccoon.engine.task.sequential.Encoding_SequentialCodingTask._codeBatch, org.msrg.raccoon.CodedPiece._codedContent, org.msrg.raccoon.engine.task.sequential.SequentialCodingTask._currentStage, org.msrg.raccoon.engine.task.sequential.SequentialCodingTask._engine, org.msrg.raccoon.engine.task.CodingTask._result, org.msrg.raccoon.matrix.bulk.SliceMatrix.createEmptyCodedPiece(), org.msrg.raccoon.CodedBatch.createNewBulkMatrix(), org.msrg.raccoon.engine.task.sequential.SequentialCodingTask.failed(), org.msrg.raccoon.matrix.finitefields.ByteMatrix.getByteArray(), org.msrg.raccoon.CodedBatch.getNewCodedCoefficients(), org.msrg.raccoon.engine.task.result.SliceMatrix_CodingResult.getResult(), org.msrg.raccoon.engine.task.result.CodingResult.isFailed(), org.msrg.raccoon.engine.task.result.CodingResult.isFinished(), org.msrg.raccoon.engine.ICodingEngine.multiply(), org.msrg.raccoon.matrix.finitefields.ByteMatrix.multiply(), org.msrg.raccoon.engine.task.sequential.SequentialCodingTask.setCurrentStage(), and org.msrg.raccoon.matrix.TypedMatrix< T >.verify().
{
         switch (_currentStage) {
             case -1:
                 CodedPiece[] codedSlices = ((ReceivedCodedBatch) _codeBatch).getCodedSlicesForCoding();
                 if (codedSlices.length == 0) {
                     failed();
                     return;
                 }
                 SliceMatrix[] rowMatrices = new SliceMatrix[codedSlices.length];
                 byte[][] bCC = new byte[codedSlices.length][];
                 for (int i = 0; i < rowMatrices.length; i++) {
                     rowMatrices[i] = codedSlices[i]._codedContent;
                     bCC[i] = codedSlices[i]._cc.getByteArray()[0];
                 }
                 BulkMatrix codedSlicesAsBulkMatrix =
                         _codeBatch.createNewBulkMatrix(rowMatrices);
                 CodedCoefficients cc =
                         _codeBatch.getNewCodedCoefficients(codedSlices.length);
                 cc.verify();
                 byte[][] bb = cc.multiply(bCC);
                 byte[] b = bb[0];
                 _cc = _codeBatch.getNewCodedCoefficients(b);
                 _cc.verify();
                 if (cc.getByteArray() == null)
                     throw new NullPointerException();
                 if (cc.getByteArray()[0] == null)
                     throw new NullPointerException();
                 _smCodingResult =
                         _engine.multiply(this, cc, codedSlicesAsBulkMatrix);
                 setCurrentStage(0);
 //          if(codedSlices==null) {
 //              setCurrentStage(0);
 //              setCurrentStage(1);
 //          } else {
 //              CodedCoefficients cc = new CodedCoefficients(codedSlices.length);
 //              SliceMatrix[] rowMatrices = new SliceMatrix[codedSlices.length];
 //              for(int i=0 ; i<rowMatrices.length ; i++)
 //                  rowMatrices[i] = codedSlices[i]._codedContent;
 //
 //              BulkMatrix combinedMultiRowMatrix = new BulkMatrix(rowMatrices);
 //              for(int i=0 ; i<codedSlices.length ; i++)
 //                  _cc = cc.multiply(codedSlices[i]._cc);
 //
 //              _cc = cc;
 //              _smCodingResult = _engine.multiply(this, _cc, combinedMultiRowMatrix);
 //
 //              setCurrentStage(0);
 //          }
                 break;
             case 0:
                 if (_smCodingResult.isFailed()) {
                     failed();
                 } else if (_smCodingResult.isFinished()) {
                     SliceMatrix sm = _smCodingResult.getResult();
                     CodedPiece codedSlice = sm.createEmptyCodedPiece(_cc, sm);
                     ((CodedSlice_CodingResult) _result).setResult(codedSlice);
                     setCurrentStage(1);
                 }
                 break;
             default:
                 throw new IllegalStateException("" + _currentStage);
         }
     }