raccoon: org.msrg.raccoon.engine.task.sequential.EncodingReceivedEncodingDecodingEqual_SequentialCodingTask.codingFinished
codingFinished()
synchronized void org.msrg.raccoon.engine.task.sequential.EncodingReceivedEncodingDecodingEqual_SequentialCodingTask.codingFinished (CodingResult result)
Implements org.msrg.raccoon.engine.ICodingListener.
Definition at line 55 of file EncodingReceivedEncodingDecodingEqual_SequentialCodingTask.java.
References org.msrg.raccoon.engine.task.sequential.SequentialCodingTask._engine, org.msrg.raccoon.ReceivedCodedBatch.addCodedSlice(), org.msrg.raccoon.engine.ICodingEngine.encode(), org.msrg.raccoon.engine.task.result.CodedSlice_CodingResult.getResult(), and org.msrg.raccoon.engine.task.sequential.EncodingReceivedEncodingDecodingEqual_SequentialCodingTask.runStagePrivately().
{
         if (result == _decodeCodingResult) {
             runStagePrivately();
             return;
         }
         if (result == _equalsCodingResult) {
             runStagePrivately();
             return;
         }
         CodedSlice_CodingResult sliceResult =
                 (CodedSlice_CodingResult) result;
         if (_activeCodingResults1.remove(result)) {
             _destCodedBatch1.addCodedSlice(sliceResult.getResult());
             CodedSlice_CodingResult sliceResult2 = _engine.encode(this, _destCodedBatch1);
             _activeCodingResults2.add(sliceResult2);
         } else if (_activeCodingResults2.remove(result)) {
             _destCodedBatch2.addCodedSlice(sliceResult.getResult());
         } else
             throw new IllegalStateException();
         runStagePrivately();
     }