raccoon: org.msrg.raccoon.engine.task.sequential.EncodingReceivedEncodingDecodingEqual_SequentialCodingTask.runStagePrivately
runStagePrivately()
void org.msrg.raccoon.engine.task.sequential.EncodingReceivedEncodingDecodingEqual_SequentialCodingTask.runStagePrivately () protected
Definition at line 96 of file EncodingReceivedEncodingDecodingEqual_SequentialCodingTask.java.
References org.msrg.raccoon.engine.task.sequential.SequentialCodingTask._currentStage, org.msrg.raccoon.engine.task.sequential.SequentialCodingTask._engine, org.msrg.raccoon.engine.task.CodingTask._result, org.msrg.raccoon.engine.ICodingEngine.checkEquality(), org.msrg.raccoon.engine.ICodingEngine.decode(), org.msrg.raccoon.engine.ICodingEngine.encode(), org.msrg.raccoon.engine.task.sequential.SequentialCodingTask.finished(), org.msrg.raccoon.SourceCodedBatch.getAvailableCodedPieceCount(), org.msrg.raccoon.CodedBatch.getBulkMatrix(), org.msrg.raccoon.engine.task.result.Equals_CodingResult.getResult(), org.msrg.raccoon.engine.task.CodingTask.isFailed(), org.msrg.raccoon.engine.task.sequential.SequentialCodingTask.reachedFinalStage(), and org.msrg.raccoon.engine.task.sequential.SequentialCodingTask.setCurrentStage().
Referenced by org.msrg.raccoon.engine.task.sequential.EncodingReceivedEncodingDecodingEqual_SequentialCodingTask.codingFinished().
{
         if (isFailed())
             return;
         switch (_currentStage) {
             case -1:
                 for (int i = 0; i < _srcCodedBatch.getAvailableCodedPieceCount() * 2; i++) {
                     CodedSlice_CodingResult encodingResult = _engine.encode(this, _srcCodedBatch);
                     _activeCodingResults1.add(encodingResult);
                 }
                 setCurrentStage(0);
                 break;
             case 0:
                 if (!_activeCodingResults1.isEmpty())
                     return;
                 if (!_activeCodingResults2.isEmpty())
                     return;
                 _decodeCodingResult = _engine.decode(this, _destCodedBatch2);
                 setCurrentStage(1);
                 break;
             case 1:
                 if (!_activeCodingResults1.isEmpty() || !_activeCodingResults2.isEmpty())
                     return;
                 _equalsCodingResult =
                         _engine.checkEquality(this, _srcCodedBatch.getBulkMatrix(), _destCodedBatch2.getBulkMatrix());
                 setCurrentStage(2);
                 break;
             case 2:
                 boolean finalResult = _equalsCodingResult.getResult();
                 ((Equals_CodingResult) _result).setResult(finalResult);
                 setCurrentStage(3);
                 break;
         }
         if (reachedFinalStage())
             finished();
     }