raccoon: org.msrg.raccoon.engine.task.sequential.Encoding_SequentialCodingTask.codingFinished
final synchronized void org.msrg.raccoon.engine.task.sequential.Encoding_SequentialCodingTask.codingFinished (CodingResult result)
Implements org.msrg.raccoon.engine.ICodingListener.
Definition at line 67 of file Encoding_SequentialCodingTask.java.
References org.msrg.raccoon.engine.task.sequential.SequentialCodingTask._engine, org.msrg.raccoon.engine.task.sequential.SequentialCodingTask.finished(), org.msrg.raccoon.engine.task.sequential.SequentialCodingTask.reachedFinalStage(), and org.msrg.raccoon.engine.task.sequential.Encoding_SequentialCodingTask.runStagePrivately().
{
         ((ICodingListener)_engine).codingFinished(result);
         runStagePrivately();
         if(reachedFinalStage())
             finished();
     }