raccoon: org.msrg.raccoon.engine.task.sequential.MultiplyInverseMultiplyEqual_SequentialCodingTask.runStagePrivately
void org.msrg.raccoon.engine.task.sequential.MultiplyInverseMultiplyEqual_SequentialCodingTask.runStagePrivately () protected
Definition at line 66 of file MultiplyInverseMultiplyEqual_SequentialCodingTask.java.
References org.msrg.raccoon.engine.task.sequential.MultiplyInverseMultiplyEqual_SequentialCodingTask._bm, org.msrg.raccoon.engine.task.sequential.SequentialCodingTask._currentStage, org.msrg.raccoon.engine.task.sequential.SequentialCodingTask._engine, org.msrg.raccoon.engine.task.CodingTask._result, org.msrg.raccoon.engine.ICodingEngine.checkEquality(), org.msrg.raccoon.engine.task.sequential.SequentialCodingTask.failed(), org.msrg.raccoon.engine.task.result.Equals_CodingResult.getResult(), org.msrg.raccoon.engine.task.result.BulkMatrix_CodingResult.getResult(), org.msrg.raccoon.engine.task.result.ByteMatrix_CodingResult.getResult(), org.msrg.raccoon.engine.ICodingEngine.inverse(), org.msrg.raccoon.engine.task.result.CodingResult.isFailed(), org.msrg.raccoon.engine.task.result.CodingResult.isFinished(), org.msrg.raccoon.engine.ICodingEngine.multiply(), and org.msrg.raccoon.engine.task.sequential.SequentialCodingTask.setCurrentStage().
Referenced by org.msrg.raccoon.engine.task.sequential.MultiplyInverseMultiplyEqual_SequentialCodingTask.codingFinished().
{
         switch (_currentStage) {
         case -1:
         {
             setCurrentStage(0);
             _multipliedSMResult =
                 (BulkMatrix_CodingResult) _engine.multiply(this, _m, _bm);
             _mInverseResult = (ByteMatrix_CodingResult) _engine.inverse(this, _m);
             break;
         }
         case 0:
         {
             if(_mInverseResult.isFinished() && _multipliedSMResult.isFinished()) {
                 setCurrentStage(1);
                 _multipliedInverseMultipliedSMResult =
                     (BulkMatrix_CodingResult) _engine.multiply(this, _mInverseResult.getResult(), _multipliedSMResult.getResult());
             }
             else if(_mInverseResult.isFailed() || _multipliedSMResult.isFailed())
                 failed();
             break;
         }
         case 1:
         {
             if(_multipliedInverseMultipliedSMResult.isFailed())
                 throw new SequentialCodingTaskFailed(this);
             else if (_multipliedInverseMultipliedSMResult.isFinished()) {
                 setCurrentStage(2);
                 _finalEqualityResult = (Equals_CodingResult) _engine.checkEquality(this, _multipliedInverseMultipliedSMResult.getResult(), _bm);
             }
             break;
         }
         case 2:
         {
             if(_finalEqualityResult.isFailed())
                 failed();
             else if (_finalEqualityResult.isFinished()) {
                 setCurrentStage(3);
                 ((Equals_CodingResult)_result).setResult(_finalEqualityResult.getResult());
             }
             break;
         }
         default:
             throw new IllegalStateException("" + _currentStage);
         }
     }