raccoon: org.msrg.raccoon.matrix.TypedMatrix.equals
equals()
boolean org.msrg.raccoon.matrix.TypedMatrix< T >.equals (Object obj)
Definition at line 422 of file TypedMatrix.java.
Referenced by org.msrg.raccoon.matrix.TypedMatrix< Byte >.equals(), org.msrg.raccoon.matrix.TypedMatrix< Byte >.hasZeroRow(), org.msrg.raccoon.matrix.finitefields.ByteMatrixTest.runTestM2timesInvIsM(), and org.msrg.raccoon.matrix.finitefields.FFByteMatrixTest.testM2timesInvIsM().
{
         if (obj == null)
             return false;
         if (!obj.getClass().isInstance(this))
             return false;
         TypedMatrix<?> tmObj = (TypedMatrix<?>) obj;
         if (_rows != tmObj._rows || _cols != tmObj._cols)
             return false;
         for (int i = 0; i < _rows; i++)
             for (int j = 0; j < _rows; j++)
                 if (!_b[i][j].equals(tmObj._b[i][j]))
                     return false;
         return true;
     }