raccoon: org.msrg.raccoon.matrix.TypedMatrix.inverseMatrix
inverseMatrix()
TypedMatrix<T> org.msrg.raccoon.matrix.TypedMatrix< T >.inverseMatrix ()
Definition at line 174 of file TypedMatrix.java.
Referenced by org.msrg.raccoon.ReceivedCodedBatch.canSolveHighPriority(), org.msrg.raccoon.ReceivedCodedBatch.decode(), org.msrg.raccoon.matrix.finitefields.ByteMatrix.isInversable(), org.msrg.raccoon.matrix.DoubleMatrix.main(), org.msrg.raccoon.engine.thread.CodingThreadImpl.runTask(), org.msrg.raccoon.matrix.finitefields.ByteMatrixTest.runTestM2timesInvIsM(), org.msrg.raccoon.matrix.finitefields.ByteMatrixTest.runTestManyInverse(), org.msrg.raccoon.matrix.finitefields.FFByteMatrixTest.testM2timesInvIsM(), org.msrg.raccoon.matrix.finitefields.ByteMatrixTest.testMtimesBMtimesInvMIsBM(), and org.msrg.raccoon.matrix.finitefields.FFByteMatrixTest.testMtimesMInvIsIdentity().
{
         synchronized (_lock) {
             if (_inverse != null)
                 return _inverse;
         }
         TypedMatrix<T> inverse = inverseMatrixPrivately();
         synchronized (_lock) {
             if (inverse == null)
                 return null;
             else if (_inverse == null)
                 _inverse = inverse;
             return _inverse;
         }
     }