raccoon: org.msrg.raccoon.matrix.TypedMatrix.verify
verify()
void org.msrg.raccoon.matrix.TypedMatrix< T >.verify ()
Definition at line 139 of file TypedMatrix.java.
Referenced by org.msrg.raccoon.matrix.finitefields.ByteMatrix1D.multiply1D(), org.msrg.raccoon.engine.task.sequential.EncodingReceivedCodedBatch_SequentialCodingTask.runStagePrivately(), org.msrg.raccoon.engine.task.sequential.EncodingSourceCodedBatch_SequentialCodingTask.runStagePrivately(), and org.msrg.raccoon.matrix.TypedMatrix< Byte >.TypedMatrix().
{
         if (!CodingEngineImpl.DEBUG)
             return;
         if (_b == null)
             throw new NullPointerException();
         for (int i = 0; i < _rows; i++) {
             if (_b[i] == null)
                 throw new NullPointerException("" + i);
             if (_b[i].length != _cols)
                 throw new IllegalArgumentException("" + i + " vs. " + _b[i].length + " vs. " + _cols);
             for (int j = 0; j < _cols && CodingEngineImpl.DEBUG; j++)
                 if (_b[i][j] == null)
                     throw new NullPointerException("" + i + " vs. " + j + "[" + _rows + "x" + _cols + "]");
         }
     }