raccoon: org.msrg.raccoon.engine.task.CodingTask.isFailed
isFailed()
boolean org.msrg.raccoon.engine.task.CodingTask.isFailed ()
Definition at line 50 of file CodingTask.java.
References org.msrg.raccoon.engine.task.CodingTaskStatus.FAILED.
Referenced by org.msrg.raccoon.engine.task.sequential.EncodingDecodingEqual_SequentialCodingTask.codingFinished(), org.msrg.raccoon.engine.CodingEngine.notifyListener(), org.msrg.raccoon.engine.thread.CodingThread.runMe(), org.msrg.raccoon.engine.task.sequential.EncodingDecodingEqual_SequentialCodingTask.runStagePrivately(), and org.msrg.raccoon.engine.task.sequential.EncodingReceivedEncodingDecodingEqual_SequentialCodingTask.runStagePrivately().
{
         return _status == CodingTaskStatus.FAILED;
     }