raccoon: org.msrg.raccoon.engine.task.CodingTask.changeStatus
void org.msrg.raccoon.engine.task.CodingTask.changeStatus (CodingTaskStatus prevAllowedStatus, CodingTaskStatus newStatus) protected
Definition at line 58 of file CodingTask.java.
References org.msrg.raccoon.engine.task.CodingTask._id, and org.msrg.raccoon.engine.task.result.CodingResult.setStatus().
Referenced by org.msrg.raccoon.engine.task.CodingTask.failed(), org.msrg.raccoon.engine.task.CodingTask.finished(), and org.msrg.raccoon.engine.task.CodingTask.started().
{
         synchronized (_id) {
             if(prevAllowedStatus != null && prevAllowedStatus != _status)
                 throw new IllegalStateException("Expected: " + prevAllowedStatus + ", found: " + _status + ", newstate: " + newStatus);
             _status = newStatus;
         }
         _result.setStatus(_status);
     }