raccoon: org.msrg.raccoon.engine.CodingEngine.notifyListener
notifyListener()
void org.msrg.raccoon.engine.CodingEngine.notifyListener (CodingTask cTask) protected
Definition at line 205 of file CodingEngine.java.
References org.msrg.raccoon.engine.task.CodingTask._listener, org.msrg.raccoon.engine.task.CodingTask._result, org.msrg.raccoon.engine.ICodingListener.codingFailed(), org.msrg.raccoon.engine.ICodingListener.codingFinished(), org.msrg.raccoon.engine.task.CodingTask.isFailed(), and org.msrg.raccoon.engine.task.CodingTask.isFinished().
Referenced by org.msrg.raccoon.engine.CodingEngine.codingTaskFailed(), org.msrg.raccoon.engine.CodingEngine.codingTaskFinished(), and org.msrg.raccoon.engine.CodingEngineImpl.processCodingEvent().
{
         ICodingListener listener = cTask._listener;
         CodingResult result = cTask._result;
         if (cTask.isFinished()) {
             if (listener != null)
                 listener.codingFinished(result);
             for (ICodingListener generalListener : _listeners)
                 generalListener.codingFinished(result);
         } else if (cTask.isFailed()) {
             if (listener != null)
                 listener.codingFailed(result);
             for (ICodingListener generalListener : _listeners)
                 generalListener.codingFailed(result);
         } else
             throw new IllegalArgumentException("" + cTask);
     }