raccoon: org.msrg.raccoon.matrix.MatrixFactory.multiply
multiply()
static TypedMatrix<?> org.msrg.raccoon.matrix.MatrixFactory.multiply (TypedMatrix m1, TypedMatrix m2) static
Definition at line 12 of file MatrixFactory.java.
References org.msrg.raccoon.matrix.TypedMatrix< T >._b, and org.msrg.raccoon.matrix.TypedMatrix< T >.multiply().
Referenced by org.msrg.raccoon.matrix.DoubleMatrix.main(), org.msrg.raccoon.matrix.DoubleMatrix.main0(), org.msrg.raccoon.matrix.finitefields.ByteMatrixTest.runTestM2timesInvIsM(), org.msrg.raccoon.matrix.finitefields.FFByteMatrixTest.testM2timesInvIsM(), and org.msrg.raccoon.matrix.finitefields.FFByteMatrixTest.testMtimesMInvIsIdentity().
{
         return m1.multiply(m2._b);
     }