raccoon: org.msrg.raccoon.matrix.DoubleMatrix.main0
main0()
static void org.msrg.raccoon.matrix.DoubleMatrix.main0 (String [] argv) static
Definition at line 97 of file DoubleMatrix.java.
References org.msrg.raccoon.matrix.MatrixFactory.add(), org.msrg.raccoon.matrix.DoubleMatrix.createRandomIntegerMatrix(), org.msrg.raccoon.matrix.DoubleMatrix.DoubleMatrix(), org.msrg.raccoon.matrix.MatrixFactory.multiply(), org.msrg.raccoon.matrix.DoubleMatrix.multiply(), org.msrg.raccoon.matrix.TypedMatrix< T >.toStringAdd(), org.msrg.raccoon.matrix.TypedMatrix< T >.toStringMult(), and org.msrg.raccoon.matrix.TypedMatrix< T >.toStringShort().
{
         System.out.println("Creating m1");
         DoubleMatrix m1 = DoubleMatrix.createRandomIntegerMatrix(10, 11);
 //      DoubleMatrix m1 = createIdentityMatrix(10);
         System.out.println("Creating m2");
         DoubleMatrix m2 = (DoubleMatrix) DoubleMatrix.createRandomIntegerMatrix(11, 12).multiply(new Float(3));
 //      DoubleMatrix m2 = (DoubleMatrix) createIdentityMatrix(10).multiply(new DoubleDataType(3));
         System.out.println("Creating m3");
         DoubleMatrix m3 = (DoubleMatrix) MatrixFactory.multiply(m1, m2);
         System.out.println("Creating m4");
         DoubleMatrix m4 = (DoubleMatrix) MatrixFactory.add(m2, m2);
         String multStr = TypedMatrix.toStringMult(m1, m2, m3);
         System.out.println(multStr);
         System.out.println();
         String addStr = TypedMatrix.toStringAdd(m2, m2, m4);
         System.out.println(addStr);
         System.out.println(m1.toStringShort());
         System.out.println(m2.toStringShort());
         System.out.println(m3.toStringShort());
         System.out.println(m4.toStringShort());
     }