raccoon: org.msrg.raccoon.matrix.DoubleMatrix.cloneExtended
TypedMatrix<Float> org.msrg.raccoon.matrix.DoubleMatrix.cloneExtended ()
Definition at line 108 of file DoubleMatrix.java.
References org.msrg.raccoon.matrix.TypedMatrix< Float >._b, org.msrg.raccoon.matrix.TypedMatrix< Float >._cols, org.msrg.raccoon.matrix.TypedMatrix< Float >._rows, org.msrg.raccoon.matrix.DoubleMatrix.clone(), org.msrg.raccoon.matrix.DoubleMatrix.DoubleMatrix(), org.msrg.raccoon.matrix.TypedMatrix< Float >.getColumnSize(), org.msrg.raccoon.matrix.DoubleMatrix.getOne(), org.msrg.raccoon.matrix.TypedMatrix< Float >.getRowSize(), and org.msrg.raccoon.matrix.DoubleMatrix.getZero().
{
         Float[][] b = new Float[_rows][_cols * 2];
         for(int i=0 ; i<getRowSize() ; i++) {
             for(int j=0 ; j<getColumnSize() ; j++)
                 b[i][j] = clone(_b[i][j]);
             for(int j=0 ; j<getColumnSize() ; j++)
                 if (i==j)
                     b[i][j + _cols] = getOne();
                 else
                     b[i][j + _cols] = getZero();
             }
         return new DoubleMatrix(b);
     }