raccoon: org.msrg.raccoon.matrix.DoubleMatrix.createRandomMatrix
createRandomMatrix()
static DoubleMatrix org.msrg.raccoon.matrix.DoubleMatrix.createRandomMatrix (DATATYPES dt, int rows, int cols) static package
Definition at line 60 of file DoubleMatrix.java.
References org.msrg.raccoon.matrix.DoubleMatrix._RANDOM, and org.msrg.raccoon.matrix.DoubleMatrix.DoubleMatrix().
Referenced by org.msrg.raccoon.matrix.DoubleMatrix.createRandomDoubleMatrix(), and org.msrg.raccoon.matrix.DoubleMatrix.createRandomIntegerMatrix().
{
         Float[][] b = new Float[rows][];
         for (int i = 0; i < b.length; i++) {
             Float[] randB = new Float[cols];
             for (int j = 0; j < randB.length; j++)
                 switch (dt) {
                     case DOUBLE:
                         randB[j] = DoubleMatrix._RANDOM.nextFloat();
                         break;
                     case INTEGER:
                         randB[j] = DoubleMatrix._RANDOM.nextFloat();
                         break;
                     default:
                         throw new UnsupportedOperationException("Unknown: " + dt);
                 }
             b[i] = randB;
         }
         return new DoubleMatrix(b);
     }