raccoon: org.msrg.raccoon.matrix.DoubleMatrix.main
static void org.msrg.raccoon.matrix.DoubleMatrix.main (String[] argv) static
Definition at line 188 of file DoubleMatrix.java.
References org.msrg.raccoon.matrix.DoubleMatrix.createMatrix(), org.msrg.raccoon.matrix.DoubleMatrix.DoubleMatrix(), org.msrg.raccoon.matrix.TypedMatrix< T >.inverseMatrix(), org.msrg.raccoon.matrix.TypedMatrix< T >.isIdentity(), and org.msrg.raccoon.matrix.MatrixFactory.multiply().
{
         DoubleMatrix m = DoubleMatrix.createMatrix(3,
                 "2,1,2,1,1,3,2,1,4"
 //              "2,1,-1,-3,-1,2,-2,1,2"// + "," +       // 1
 //              "2,1,-1,-3,-1,2,-2,1,2" + "," +     // 2
 //              "2,1,-1,-3,-1,2,-2,1,2" + "," +     // 3
 //              "2,1,-1,-3,1,2,-2,1,2" + "," +      // 4
 //              "2,1,-1,-3,-1,2,-2,1,2" + "," +     // 5
 //              "2,1,-1,-3,-1,2,-2,1,2" + "," +     // 6
 //              "2,1,-1,-3,-1,2,-2,1,2" + "," +     // 7
 //              "2,10,-1,-3,-1,2,-2,1,2" + "," +    // 8
 //              "2,1,-1,-3,-1,2,-2,1,2"             // 9
                 );
 //      DoubleMatrix m = DoubleMatrix.createRandomSquareIntegerMatrix(30);
         System.out.println(m);
         System.out.println();
         DoubleMatrix mInv = (DoubleMatrix) m.inverseMatrix();
         System.out.println(mInv);
         System.out.println();
         DoubleMatrix mTimesMInv = (DoubleMatrix) MatrixFactory.multiply(m, mInv);
         System.out.println(mTimesMInv);
         System.out.println(mTimesMInv.isIdentity());
     }