raccoon: org.msrg.raccoon.matrix.DoubleMatrix.DoubleMatrix
org.msrg.raccoon.matrix.DoubleMatrix.DoubleMatrix (Float b[][])
Definition at line 18 of file DoubleMatrix.java.
Referenced by org.msrg.raccoon.matrix.DoubleMatrix.clone(), org.msrg.raccoon.matrix.DoubleMatrix.cloneExtended(), org.msrg.raccoon.matrix.DoubleMatrix.createIdentityMatrix(), org.msrg.raccoon.matrix.DoubleMatrix.createMatrix(), org.msrg.raccoon.matrix.DoubleMatrix.createRandomMatrix(), org.msrg.raccoon.matrix.DoubleMatrix.decloneExtended(), org.msrg.raccoon.matrix.DoubleMatrix.getZeroMatrix(), org.msrg.raccoon.matrix.DoubleMatrix.main(), and org.msrg.raccoon.matrix.DoubleMatrix.main0().
{
         super(b);
     }