raccoon: org.msrg.raccoon.matrix.DoubleMatrix.clone
clone() [1/2]
DoubleMatrix org.msrg.raccoon.matrix.DoubleMatrix.clone ()
Definition at line 195 of file DoubleMatrix.java.
References org.msrg.raccoon.matrix.TypedMatrix< Float >._b, org.msrg.raccoon.matrix.TypedMatrix< Float >._cols, org.msrg.raccoon.matrix.TypedMatrix< Float >._rows, org.msrg.raccoon.matrix.DoubleMatrix.DoubleMatrix(), org.msrg.raccoon.matrix.TypedMatrix< Float >.getColumnSize(), and org.msrg.raccoon.matrix.TypedMatrix< Float >.getRowSize().
Referenced by org.msrg.raccoon.matrix.DoubleMatrix.cloneExtended(), and org.msrg.raccoon.matrix.DoubleMatrix.decloneExtended().
{
         Float[][] b = new Float[_rows][_cols];
         for (int i = 0; i < getRowSize(); i++)
             for (int j = 0; j < getColumnSize(); j++)
                 b[i][j] = clone(_b[i][j]);
         return new DoubleMatrix(b);
     }