raccoon: org.msrg.raccoon.engine.thread.CodingThread.runMe
runMe()
final void org.msrg.raccoon.engine.thread.CodingThread.runMe (CodingTask codingTask) protected
Definition at line 49 of file CodingThread.java.
References org.msrg.raccoon.engine.CodingEngine.codingTaskFailed(), org.msrg.raccoon.engine.CodingEngine.codingTaskFinished(), org.msrg.raccoon.engine.CodingEngine.codingTaskStarted(), org.msrg.raccoon.engine.task.CodingTask.failed(), org.msrg.raccoon.engine.task.CodingTask.isFailed(), org.msrg.raccoon.engine.task.CodingTask.isFinished(), org.msrg.raccoon.engine.task.CodingTask.isSequencial(), org.msrg.raccoon.engine.thread.CodingThread.runTask(), and org.msrg.raccoon.engine.task.CodingTask.started().
Referenced by org.msrg.raccoon.engine.thread.CodingThread.run().
{
         try {
             codingTask.started();
             _engine.codingTaskStarted(this, codingTask);
             runTask(codingTask);
         } catch (Exception x) {
             codingTask.failed();
             x.printStackTrace();
         }
         if (codingTask.isFailed()) {
             if (!codingTask.isSequencial())
                 _engine.codingTaskFailed(this, codingTask);
         } else if (codingTask.isFinished()) {
             if (!codingTask.isSequencial())
                 _engine.codingTaskFinished(this, codingTask);
         }
     }