raccoon: org.msrg.raccoon.utils.BytesUtil.hex
static String org.msrg.raccoon.utils.BytesUtil.hex (byte b) static
Definition at line 16 of file BytesUtil.java.
Referenced by org.msrg.raccoon.CodedCoefficients.toString(), org.msrg.raccoon.CodedBatch.toString(), org.msrg.raccoon.matrix.bulk.SliceMatrix.toString(), and org.msrg.raccoon.ReceivedCodedBatch.toString().
{
         return dig[(b & 0xff) >> 4] + dig[b & 0x0f];
     }