raccoon: org.msrg.raccoon.engine.task.sequential.MultiplyBulkMatrix_SequentialCodingTask.runStagePrivately
void org.msrg.raccoon.engine.task.sequential.MultiplyBulkMatrix_SequentialCodingTask.runStagePrivately () protected
Definition at line 75 of file MultiplyBulkMatrix_SequentialCodingTask.java.
References org.msrg.raccoon.matrix.bulk.SliceMatrix._cols, org.msrg.raccoon.matrix.bulk.BulkMatrix._cols, org.msrg.raccoon.engine.task.sequential.SequentialCodingTask._currentStage, org.msrg.raccoon.engine.task.sequential.SequentialCodingTask._engine, org.msrg.raccoon.engine.task.CodingTask._result, org.msrg.raccoon.matrix.bulk.BulkMatrix.add(), org.msrg.raccoon.matrix.bulk.BulkMatrix.createEmptyMatrix(), org.msrg.raccoon.engine.task.result.SliceMatrix_CodingResult.getResult(), org.msrg.raccoon.matrix.TypedMatrix< T >.getRowSize(), org.msrg.raccoon.engine.ICodingEngine.multiply(), org.msrg.raccoon.engine.task.sequential.SequentialCodingTask.setCurrentStage(), and org.msrg.raccoon.matrix.TypedMatrix< T >.toArray().
Referenced by org.msrg.raccoon.engine.task.sequential.MultiplyBulkMatrix_SequentialCodingTask.codingFinished().
{
         switch (_currentStage) {
         case -1:
         {
             setCurrentStage(0);
             int rows = _m.getRowSize();
             _multipliedSMResultsSet = new HashSet<SliceMatrix_CodingResult>();
             _multipliedSMResults = new SliceMatrix_CodingResult[rows];
             if (rows==0) {
                 setCurrentStage(1);
             } else {
                 for(int i=0 ; i<rows ; i++) {
                     Byte[] b = _m.toArray()[i];
                     if(b == null)
                         throw new NullPointerException("" + i);
                     SliceMatrix_CodingResult smCodingResult =
                         (SliceMatrix_CodingResult) _engine.multiply(this,
                                 new ByteMatrix1D(b), _bm);
                     _multipliedSMResultsSet.add(smCodingResult);
                     _multipliedSMResults[i] = smCodingResult;
                 }
             }
             break;
         }
         case 0:
         {
             if(_multipliedSMResultsSet.isEmpty()) {
                 int reultSlices = _multipliedSMResults.length;
                 int sliceOffset = 0;
                 int rows = _m.getRowSize();
                 BulkMatrix bmResult;
                 if(rows==1)
                     bmResult = _bm.createEmptyMatrix(rows, _bm._cols);
                     //new BulkMatrix1D(_bm._cols);
                 else
                     bmResult = _bm.createEmptyMatrix(_m.getRowSize(), _bm._cols);
 //                  bmResult = new BulkMatrix(_m.getRowSize(), _bm._cols);
                 for(int i=0 ; i<reultSlices ; i++) {
                     SliceMatrix sm = _multipliedSMResults[i].getResult();
                     bmResult.add(i, sm);
                     sliceOffset += sm._cols;
                 }
                 ((BulkMatrix_CodingResult)_result).setResult(bmResult);
                 setCurrentStage(1);
             }
             break;
         }
         default:
             throw new IllegalStateException("" + _currentStage);
         }
     }