raccoon: org.msrg.raccoon.matrix.finitefields.ByteMatrix1D.multiply1D
SliceMatrix org.msrg.raccoon.matrix.finitefields.ByteMatrix1D.multiply1D (BulkMatrix bm)
Definition at line 35 of file ByteMatrix1D.java.
References org.msrg.raccoon.matrix.TypedMatrix< T >._b, org.msrg.raccoon.matrix.TypedMatrix< T >._cols, org.msrg.raccoon.matrix.bulk.BulkMatrix._cols, org.msrg.raccoon.matrix.bulk.BulkMatrix._rows, org.msrg.raccoon.matrix.finitefields.FFByteMatrix._tables, org.msrg.raccoon.matrix.bulk.BulkMatrix.createOneEmtpySlice(), org.msrg.raccoon.finitefields.Tables.EXP, org.msrg.raccoon.matrix.bulk.BulkMatrix.getContent(), org.msrg.raccoon.matrix.bulk.SliceMatrix.loadNoCopy(), org.msrg.raccoon.finitefields.Tables.LOG, and org.msrg.raccoon.matrix.TypedMatrix< T >.verify().
Referenced by org.msrg.raccoon.engine.thread.CodingThreadImpl.runTask().
{
         if(_cols != bm._rows)
             throw new IllegalArgumentException("Mismatch: " + _cols + " vs. " + bm._rows);
         SliceMatrix outputSlice = bm.createOneEmtpySlice(bm._cols);
         byte[][] bIn = bm.getContent();
         verify();
         byte[] bRow = new byte[bm._cols];
         for(int j=0 ; j<bm._cols ; j++) {
             for(int k=0 ; k<_cols ; k++) {
                 byte a = _b[0][k];
                 byte b = bIn[k][j];
 //              byte mult = _tables.FFMulFast(a, b);
                 byte mult;
                 if(a==0||b==0) {
                     mult = 0;
                 } else {
                    int t = ((_tables.LOG[(a & 0xff)] & 0xff) + (_tables.LOG[(b & 0xff)] & 0xff));
                    mult = _tables.EXP[((t>255)?t-255:t) & 0xff];
                 }
                 bRow[j] ^= (byte)(mult);
             }
         }
         outputSlice.loadNoCopy(bRow);
         return outputSlice;
     }