raccoon: org.msrg.raccoon.matrix.bulk.SliceMatrix.loadWithCopy
loadWithCopy()
void org.msrg.raccoon.matrix.bulk.SliceMatrix.loadWithCopy (byte [] b, int bStartOffset)
Definition at line 72 of file SliceMatrix.java.
References org.msrg.raccoon.matrix.bulk.SliceMatrix._cols.
Referenced by org.msrg.raccoon.matrix.bulk.SliceMatrix.clone(), org.msrg.raccoon.matrix.bulk.BulkMatrix.createBulkMatixRandomData(), and org.msrg.raccoon.matrix.bulk.BulkMatrix1D.createBulkMatrix1D().
{
         if (_b != null)
             throw new IllegalStateException();
         _b = new byte[_cols];
         for (int j = 0; j < _cols; j++)
             _b[j] = b[bStartOffset + j];
     }