raccoon: org.msrg.raccoon.matrix.bulk.SliceMatrix.equals
boolean org.msrg.raccoon.matrix.bulk.SliceMatrix.equals (Object obj)
Definition at line 101 of file SliceMatrix.java.
References org.msrg.raccoon.matrix.bulk.SliceMatrix._b, org.msrg.raccoon.matrix.bulk.SliceMatrix._cols, and org.msrg.raccoon.matrix.bulk.SliceMatrix.SliceMatrix().
Referenced by org.msrg.raccoon.CodedPiece.equals(), and org.msrg.raccoon.engine.thread.CodingThreadImpl.runTask().
{
         if(obj==null)
             return false;
         if(!getClass().isAssignableFrom(obj.getClass()))
             return false;
         SliceMatrix smObj = (SliceMatrix) obj;
         if (_cols != smObj._cols)
             return false;
         for(int j=0 ; j<_cols ; j++)
             if(_b[j] != smObj._b[j])
                 return false;
         return true;
     }