raccoon: org.msrg.raccoon.engine.task.sequential.BulkMatrixEqual_CodingTask.codingFinished
codingFinished()
synchronized void org.msrg.raccoon.engine.task.sequential.BulkMatrixEqual_CodingTask.codingFinished (CodingResult result)
Implements org.msrg.raccoon.engine.ICodingListener.
Definition at line 46 of file BulkMatrixEqual_CodingTask.java.
References org.msrg.raccoon.engine.task.sequential.SequentialCodingTask._engine, org.msrg.raccoon.engine.task.sequential.SequentialCodingTask.finished(), org.msrg.raccoon.engine.task.sequential.SequentialCodingTask.reachedFinalStage(), and org.msrg.raccoon.engine.task.sequential.BulkMatrixEqual_CodingTask.runStagePrivately().
{
         ((ICodingListener) _engine).codingFinished(result);
         if (!_slicesEqualityResultsSet.remove(result))
             throw new IllegalStateException(result.toString());
         runStagePrivately();
         if (reachedFinalStage())
             finished();
     }