raccoon: org.msrg.raccoon.engine.task.sequential.BulkMatrixEqual_CodingTask.runStagePrivately
runStagePrivately()
void org.msrg.raccoon.engine.task.sequential.BulkMatrixEqual_CodingTask.runStagePrivately () protected
Definition at line 62 of file BulkMatrixEqual_CodingTask.java.
References org.msrg.raccoon.matrix.bulk.BulkMatrix._cols, org.msrg.raccoon.engine.task.sequential.SequentialCodingTask._currentStage, org.msrg.raccoon.engine.task.sequential.SequentialCodingTask._engine, org.msrg.raccoon.engine.task.CodingTask._result, org.msrg.raccoon.matrix.bulk.BulkMatrix._rows, org.msrg.raccoon.engine.ICodingEngine.checkEquality(), org.msrg.raccoon.matrix.bulk.BulkMatrix.getSliceCount(), org.msrg.raccoon.engine.task.sequential.SequentialCodingTask.setCurrentStage(), and org.msrg.raccoon.matrix.bulk.BulkMatrix.slice().
Referenced by org.msrg.raccoon.engine.task.sequential.BulkMatrixEqual_CodingTask.codingFinished().
{
         switch (_currentStage) {
             case -1:
                 int slices1 = _bm1.getSliceCount();
                 int slices2 = _bm2.getSliceCount();
                 if (_bm1._cols != _bm2._cols || _bm1._rows != _bm2._rows || slices1 != slices2) {
                     ((Equals_CodingResult) _result).setResult(false);
                     setCurrentStage(0);
                     setCurrentStage(1);
                 } else {
                     _slicesEqualityResults = new Equals_CodingResult[slices1];
                     _slicesEqualityResultsSet = new HashSet<Equals_CodingResult>();
                     for (int i = 0; i < slices1; i++) {
                         SliceMatrix sm1 = _bm1.slice(i);
                         SliceMatrix sm2 = _bm2.slice(i);
                         Equals_CodingResult sliceEqualityResult = _engine.checkEquality(this, sm1, sm2);
                         _slicesEqualityResultsSet.add(sliceEqualityResult);
                         _slicesEqualityResults[i] = sliceEqualityResult;
                     }
                     setCurrentStage(0);
                 }
                 break;
             case 0:
                 if (_slicesEqualityResultsSet.isEmpty()) {
                     boolean result = true;
                     for (int i = 0; i < _slicesEqualityResults.length && result; i++)
                         if (!_slicesEqualityResults[i].getResult())
                             result = false;
                     ((Equals_CodingResult) _result).setResult(result);
                     setCurrentStage(1);
                 }
                 break;
             default:
                 throw new IllegalStateException("" + _currentStage);
         }
     }