raccoon: org.msrg.raccoon.matrix.finitefields.FFByteMatrixTest.testMtimesMInvIsIdentity
testMtimesMInvIsIdentity()
void org.msrg.raccoon.matrix.finitefields.FFByteMatrixTest.testMtimesMInvIsIdentity ()
Definition at line 62 of file FFByteMatrixTest.java.
References org.msrg.raccoon.matrix.finitefields.FFByteMatrix.createRandomSquareByteMatrix(), org.msrg.raccoon.matrix.TypedMatrix< T >.inverseMatrix(), org.msrg.raccoon.matrix.TypedMatrix< T >.isIdentity(), and org.msrg.raccoon.matrix.MatrixFactory.multiply().
{
         System.out.println("***** " + "testMtimesMInvIsIdentity");
         System.out.print("Creating...");
         long start = System.currentTimeMillis();
         FFByteMatrix m = FFByteMatrix.createRandomSquareByteMatrix(matrixSize);
         long end = System.currentTimeMillis();
         System.out.println(" " + (end - start) + "ms.");
         System.out.print("Inversing ...");
         start = System.currentTimeMillis();
         FFByteMatrix mInv = (FFByteMatrix) m.inverseMatrix();
         end = System.currentTimeMillis();
         System.out.println(" " + (end - start) + "ms.");
         System.out.print("Verifying ...");
         start = System.currentTimeMillis();
         FFByteMatrix mTimesMInv = (FFByteMatrix) MatrixFactory.multiply(m, mInv);
         end = System.currentTimeMillis();
         System.out.println(" " + (end - start) + "ms.");
         assertTrue(mTimesMInv.isIdentity());
         System.out.println("OK!");
         System.out.println();
     }