raccoon: org.msrg.raccoon.engine.task.result.Equals_CodingResult.getResult
getResult()
boolean org.msrg.raccoon.engine.task.result.Equals_CodingResult.getResult ()
Definition at line 20 of file Equals_CodingResult.java.
References org.msrg.raccoon.engine.task.result.Equals_CodingResult._equals, and org.msrg.raccoon.engine.task.result.CodingResult.isFinished().
Referenced by org.msrg.raccoon.engine.task.sequential.MultiplyInverseMultiplyEqual_SequentialCodingTask.runStagePrivately(), org.msrg.raccoon.engine.task.sequential.EncodingDecodingEqual_SequentialCodingTask.runStagePrivately(), and org.msrg.raccoon.engine.task.sequential.EncodingReceivedEncodingDecodingEqual_SequentialCodingTask.runStagePrivately().
{
         if (!isFinished())
             throw new IllegalStateException();
         return _equals;
     }