raccoon: org.msrg.raccoon.engine.task.result.Equals_CodingResult.setResult
setResult()
void org.msrg.raccoon.engine.task.result.Equals_CodingResult.setResult (boolean equals)
Definition at line 27 of file Equals_CodingResult.java.
References org.msrg.raccoon.engine.task.result.CodingResult.equals(), org.msrg.raccoon.engine.task.result.CodingResult.isFailed(), and org.msrg.raccoon.engine.task.result.CodingResult.isFinished().
{
         if (isFinished())
             throw new IllegalStateException();
         if (isFailed())
             throw new IllegalStateException();
         _equals = equals;
     }