raccoon: org.msrg.raccoon.engine.task.sequential.Decoding_SequentialCodingTask.runStagePrivately
runStagePrivately()
void org.msrg.raccoon.engine.task.sequential.Decoding_SequentialCodingTask.runStagePrivately () protected
Definition at line 63 of file Decoding_SequentialCodingTask.java.
References org.msrg.raccoon.engine.task.sequential.SequentialCodingTask._currentStage, org.msrg.raccoon.engine.task.sequential.SequentialCodingTask._engine, org.msrg.raccoon.engine.task.CodingTask._listener, org.msrg.raccoon.engine.task.CodingTask._result, org.msrg.raccoon.ReceivedCodedBatch.canSolve(), org.msrg.raccoon.engine.ICodingListener.codingPreliminaryStageCompleted(), org.msrg.raccoon.CodedBatch.createNewBulkMatrix(), org.msrg.raccoon.engine.task.sequential.SequentialCodingTask.failed(), org.msrg.raccoon.ReceivedCodedBatch.getInverseCoefficientsForSolvingCodedSlices(), org.msrg.raccoon.engine.task.result.BulkMatrix_CodingResult.getResult(), org.msrg.raccoon.engine.task.result.CodingResult.isFailed(), org.msrg.raccoon.engine.task.CodingTask.isFinished(), org.msrg.raccoon.engine.task.result.CodingResult.isFinished(), org.msrg.raccoon.ReceivedCodedBatch.isSolved(), org.msrg.raccoon.engine.ICodingEngine.multiply(), org.msrg.raccoon.ReceivedCodedBatch.setContent(), and org.msrg.raccoon.engine.task.sequential.SequentialCodingTask.setCurrentStage().
Referenced by org.msrg.raccoon.engine.task.sequential.Decoding_SequentialCodingTask.codingFinished().
{
         if (isFinished())
             return;
         switch (_currentStage) {
             case -1:
                 if (_receivedCodeBatch.isSolved()) {
                     ((Equals_CodingResult) _result).setResult(true);
                     setCurrentStage(0);
                     setCurrentStage(1);
                     return;
                 }
                 CodedPiece[] solvingCodedSlices = _receivedCodeBatch.canSolve();
                 if (solvingCodedSlices == null) {
                     ((Equals_CodingResult) _result).setResult(false);
                     setCurrentStage(0);
                     setCurrentStage(1);
                     return;
                 }
                 _listener.codingPreliminaryStageCompleted(_result);
                 // Now solve the equations
                 BulkMatrix contentMatrix = _receivedCodeBatch.createNewBulkMatrix(solvingCodedSlices);
                 ByteMatrix coefficientsMatrixInverse2 = _receivedCodeBatch.getInverseCoefficientsForSolvingCodedSlices();
                 if (coefficientsMatrixInverse2 == null)
                     throw new IllegalStateException();
                 _decodedBMResult = _engine.multiply(this, coefficientsMatrixInverse2, contentMatrix);
                 setCurrentStage(0);
                 break;
             case 0:
                 if (_decodedBMResult.isFailed()) {
                     failed();
                 } else if (_decodedBMResult.isFinished()) {
                     BulkMatrix content = _decodedBMResult.getResult();
                     _receivedCodeBatch.setContent(content);
                     ((Equals_CodingResult) _result).setResult(true);
                     setCurrentStage(1);
                 }
                 break;
             default:
                 throw new IllegalStateException("" + _currentStage);
         }
     }