raccoon: org.msrg.raccoon.matrix.bulk.BulkMatrix1D.createBulkMatrix1D
createBulkMatrix1D()
static BulkMatrix1D org.msrg.raccoon.matrix.bulk.BulkMatrix1D.createBulkMatrix1D (byte [] b, int bOffset, int size) static
Definition at line 20 of file BulkMatrix1D.java.
References org.msrg.raccoon.matrix.bulk.BulkMatrix1D.BulkMatrix1D(), org.msrg.raccoon.matrix.bulk.SliceMatrix.loadWithCopy(), and org.msrg.raccoon.matrix.bulk.BulkMatrix.slice().
Referenced by org.msrg.raccoon.CodedBatchTest.setUp().
{
         BulkMatrix1D bm1d = new BulkMatrix1D(size);
         SliceMatrix sm = bm1d.slice(0);
         sm.loadWithCopy(b, bOffset);
         return bm1d;
     }