raccoon: org.msrg.raccoon.engine.CodingEngineTest.waitToFinishTasks
waitToFinishTasks()
void org.msrg.raccoon.engine.CodingEngineTest.waitToFinishTasks () protected
Definition at line 359 of file CodingEngineTest.java.
References org.msrg.raccoon.engine.CodingEngineTest._allCodingResults, org.msrg.raccoon.engine.CodingEngineTest.checkTestEnd(), org.msrg.raccoon.engine.CodingEngineTest.getStatistics(), and org.msrg.raccoon.engine.CodingEngineTest.MAX_WAIT_TIME_SMALL.
Referenced by org.msrg.raccoon.engine.CodingEngineTest.testEngine().
{
         try {
             synchronized (_allCodingResults) {
                 for (int i = 0; i < MAX_WAIT_TIME_LARGE / MAX_WAIT_TIME_SMALL && !checkTestEnd(); i++) {
                     System.out.print(getStatistics());
                     System.out.println(", LT" + ((CodingEngine) _engine).getLateThreads());
                     _allCodingResults.wait(CodingEngineTest.MAX_WAIT_TIME_SMALL);
                 }
                 if (!checkTestEnd())
                     throw new IllegalStateException("It is taking a long time..(" + getStatistics() + ")");
                 else {
                 }
             }
         } catch (InterruptedException itx) {
             itx.printStackTrace();
         }
     }