raccoon: org.msrg.raccoon.engine.CodingEngineTest.testEngine
testEngine()
void org.msrg.raccoon.engine.CodingEngineTest.testEngine ()
Definition at line 305 of file CodingEngineTest.java.
References org.msrg.raccoon.engine.CodingEngineTest._testType, org.msrg.raccoon.engine.CodingEngineTest.generateCodingTasks(), org.msrg.raccoon.engine.CodingEngineTest.generateEncodingDecodingEqualTasks(), org.msrg.raccoon.engine.CodingEngineTest.generateEncodingReceivedEncodingDecodingEqualTasks(), org.msrg.raccoon.engine.CodingEngineTest.generateEncodingTasks(), org.msrg.raccoon.engine.CodingEngineTest.generateEqualityCodingTasks(), org.msrg.raccoon.engine.CodingEngineTest.generateFullMultiplyTasks(), org.msrg.raccoon.engine.CodingEngineTest.generatePageInPageOutEqualsCodingTasks(), org.msrg.raccoon.engine.CodingEngineTest.generateSequenctialCodingTasks(), org.msrg.raccoon.engine.CodingEngineTest.getStatistics(), org.msrg.raccoon.engine.CodingEngineTest.TASK_SIZE, and org.msrg.raccoon.engine.CodingEngineTest.waitToFinishTasks().
{
         _start = System.currentTimeMillis();
         Collection<CodingTask> mainTasks;
         switch (CodingEngineTest._testType) {
             case TEST_PAGEIN_PAGEOUT_EQUALS_TASKS:
                 mainTasks = generatePageInPageOutEqualsCodingTasks(CodingEngineTest.TASK_SIZE);
                 break;
             case TEST_CODING_TASKS:
                 mainTasks = generateCodingTasks(CodingEngineTest.TASK_SIZE);
                 break;
             case TEST_SEQUENTIAL_CODING_TASKS:
                 mainTasks = generateSequenctialCodingTasks(CodingEngineTest.TASK_SIZE);
                 break;
             case TEST_FULL_MULTYPLY_TASKS:
                 mainTasks = generateFullMultiplyTasks(CodingEngineTest.TASK_SIZE);
                 break;
             case TEST_EQUALITY_TASKS:
                 mainTasks = generateEqualityCodingTasks(CodingEngineTest.TASK_SIZE);
                 break;
             case TEST_ENCODING_TASKS:
                 mainTasks = generateEncodingTasks(CodingEngineTest.TASK_SIZE);
                 break;
             case TEST_ENCODING_DECODING_EQUALS_TASKS:
                 mainTasks = generateEncodingDecodingEqualTasks(CodingEngineTest.TASK_SIZE);
                 break;
             case TEST_ENCODING_RECEIVED_ENCODING_DECODING_EQUALS_TASKS:
                 mainTasks = generateEncodingReceivedEncodingDecodingEqualTasks(CodingEngineTest.TASK_SIZE);
                 break;
             default:
                 throw new UnsupportedOperationException("Unknown test type: " + CodingEngineTest._testType);
         }
         _mainTasks.addAll(mainTasks);
         waitToFinishTasks();
         switch (CodingEngineTest._testType) {
             case TEST_ENCODING_RECEIVED_ENCODING_DECODING_EQUALS_TASKS:
                 System.out.println("Final result: " + _mainTasks.iterator().next()._result);
                 break;
             default:
                 break;
         }
         System.out.println("ALL TASKS FINISHED (" + getStatistics() + ").");
     }