raccoon: org.msrg.raccoon.engine.CodingEngineTest.setUp
setUp()
void org.msrg.raccoon.engine.CodingEngineTest.setUp ()
Definition at line 75 of file CodingEngineTest.java.
References org.msrg.raccoon.engine.CodingEngineTest._testType, org.msrg.raccoon.engine.CodingEngineTest.COLS, org.msrg.raccoon.matrix.bulk.BulkMatrix.createBulkMatixIncrementalData(), org.msrg.raccoon.matrix.finitefields.ByteMatrix.createRandomByteMatrix(), org.msrg.raccoon.matrix.bulk.SliceMatrix.createRandomSliceMatrix(), org.msrg.raccoon.engine.ICodingEngine.init(), org.msrg.raccoon.engine.ICodingEngine.registerCodingListener(), org.msrg.raccoon.engine.CodingEngineTest.ROWS, org.msrg.raccoon.engine.ICodingEngine.startComponent(), org.msrg.raccoon.engine.CodingEngineTest.TASK_SIZE, and org.msrg.raccoon.engine.CodingEngineTest.THREAD_COUNT.
{
         System.out.println("Workload: " + ROWS * COLS + " x " + CodingEngineTest.TASK_SIZE + " x " + CodingEngineTest.THREAD_COUNT);
         switch (CodingEngineTest._testType) {
             case TEST_PAGEIN_PAGEOUT_EQUALS_TASKS:
                 throw new UnsupportedOperationException();
 //          _engine = new FileCodingEngine_ForTest(THREAD_COUNT, _filename);
 //          _engine.init();
 //
 //          _sm = FileSliceMatrix.createRandomSliceMatrix(MATRIX_SIZE, SLICE_WIDTH, 0, ((FileCodingEngineImpl)_engine).getFileTable());
 //          _bm = FileBulkMatrix.createBulkMatixRandomData(ROWS, PIECE_WIDTH, ((FileCodingEngineImpl)_engine).getFileTable());
 //          break;
             default:
                 _engine = new CodingEngine_ForTest(CodingEngineTest.THREAD_COUNT);
                 _engine.init();
                 _sm = SliceMatrix.createRandomSliceMatrix(CodingEngineTest.COLS);
 //          _bm = BulkMatrix.createBulkMatixRandomData(ROWS, COLS);
                 _bm = BulkMatrix.createBulkMatixIncrementalData(CodingEngineTest.ROWS, CodingEngineTest.COLS);
         }
         _m = ByteMatrix.createRandomByteMatrix(CodingEngineTest.ROWS, CodingEngineTest.ROWS);
         _sourceCodedBatch = new SourceCodedBatch(_bm);
         _engine.registerCodingListener(this);
         _engine.startComponent();
 //      _multipliedBM = _m.multiply(_bm);
         System.out.println("Setup finished, running test: " + CodingEngineTest._testType);
     }