raccoon: org.msrg.raccoon.engine.CodingEngineTest.codingFinished
codingFinished()
void org.msrg.raccoon.engine.CodingEngineTest.codingFinished (CodingResult result)
Implements org.msrg.raccoon.engine.ICodingListener.
Definition at line 220 of file CodingEngineTest.java.
References org.msrg.raccoon.engine.CodingEngineTest._allCodingResults, org.msrg.raccoon.engine.task.result.CodingResult._cTask, org.msrg.raccoon.engine.CodingEngineTest._subfinished, org.msrg.raccoon.engine.CodingEngineTest.checkTestEnd(), org.msrg.raccoon.engine.task.result.CodingResult.isFinished(), org.msrg.raccoon.engine.CodingEngineTest.print(), org.msrg.raccoon.engine.CodingEngineTest.processFinishedResult(), and org.msrg.raccoon.engine.CodingEngineTest.reportTaskFinishTimes().
{
         print(result, "FINISHED");
         synchronized (_allCodingResults) {
             if (!result.isFinished())
                 throw new IllegalStateException(result.toString());
             processFinishedResult(result);
             if (_allCodingResults.remove(result) != null)
                 _finished++;
             else
                 _subfinished++;
         }
         reportTaskFinishTimes(result._cTask);
         checkTestEnd();
     }