raccoon: org.msrg.raccoon.engine.CodingEngineTest.processFinishedResult
processFinishedResult()
void org.msrg.raccoon.engine.CodingEngineTest.processFinishedResult (CodingResult result) protected
Definition at line 259 of file CodingEngineTest.java.
References org.msrg.raccoon.CodedPiece._codedContent, org.msrg.raccoon.engine.task.result.CodingResult._resultsType, org.msrg.raccoon.engine.CodingEngineTest._testType, org.msrg.raccoon.engine.CodingEngineTest._unequals, org.msrg.raccoon.engine.CodingEngine.DEBUG, org.msrg.raccoon.matrix.bulk.BulkMatrix.equals(), org.msrg.raccoon.engine.task.result.BulkMatrix_CodingResult.getResult(), org.msrg.raccoon.engine.task.result.CodedSlice_CodingResult.getResult(), and org.msrg.raccoon.engine.CodingEngineTestType.TEST_FULL_MULTYPLY_TASKS.
Referenced by org.msrg.raccoon.engine.CodingEngineTest.codingFinished().
{
         switch (result._resultsType) {
             case BOOLEAN:
                 if (((Equals_CodingResult) result).getResult())
                     _equals++;
                 else
                     _unequals++;
                 break;
             case BULK_MATRIX: {
                 BulkMatrix_CodingResult smResult = (BulkMatrix_CodingResult) result;
                 BulkMatrix sm = smResult.getResult();
                 if (CodingEngineTest._testType == CodingEngineTestType.TEST_FULL_MULTYPLY_TASKS && !_multipliedBM.equals(sm))
                     throw new IllegalStateException("BulkMatrix is not equal to the product!");
                 break;
             }
             case CODED_SLICE_MATRIX:
                 CodedSlice_CodingResult smResult = (CodedSlice_CodingResult) result;
                 CodedPiece sm = smResult.getResult();
                 if (CodingEngine.DEBUG)
                     System.out.println(sm._codedContent);
                 break;
             default:
                 break;
         }
     }