raccoon: org.msrg.raccoon.engine.CodingEngineTest.print
void org.msrg.raccoon.engine.CodingEngineTest.print (CodingResult result, String comment) protected
Definition at line 306 of file CodingEngineTest.java.
References org.msrg.raccoon.engine.CodingEngineTest._allCodingResults, and org.msrg.raccoon.engine.CodingEngine.DEBUG.
Referenced by org.msrg.raccoon.engine.CodingEngineTest.codingFailed(), org.msrg.raccoon.engine.CodingEngineTest.codingFinished(), and org.msrg.raccoon.engine.CodingEngineTest.codingStarted().
{
         String str;
         synchronized (_allCodingResults) {
             str = _allCodingResults.get(result);
         }
         if(CodingEngine.DEBUG)
             System.out.println(comment + ": " + result + ":" + str);
     }