raccoon: org.msrg.raccoon.engine.task.sequential.SequentialCodingTask.setCurrentStage
setCurrentStage()
final void org.msrg.raccoon.engine.task.sequential.SequentialCodingTask.setCurrentStage (int i) protected
Definition at line 82 of file SequentialCodingTask.java.
Referenced by org.msrg.raccoon.engine.task.sequential.EncodingDecodingEqual_SequentialCodingTask.EncodingDecodingEqual_SequentialCodingTask(), org.msrg.raccoon.engine.task.sequential.EncodingReceivedCodedBatch_SequentialCodingTask.runStagePrivately(), org.msrg.raccoon.engine.task.sequential.EncodingSourceCodedBatch_SequentialCodingTask.runStagePrivately(), org.msrg.raccoon.engine.task.sequential.MultiplyInverseMultiplyEqual_SequentialCodingTask.runStagePrivately(), org.msrg.raccoon.engine.task.sequential.BulkMatrixEqual_CodingTask.runStagePrivately(), org.msrg.raccoon.engine.task.sequential.Decoding_SequentialCodingTask.runStagePrivately(), org.msrg.raccoon.engine.task.sequential.MultiplyBulkMatrix_SequentialCodingTask.runStagePrivately(), org.msrg.raccoon.engine.task.sequential.EncodingDecodingEqual_SequentialCodingTask.runStagePrivately(), and org.msrg.raccoon.engine.task.sequential.EncodingReceivedEncodingDecodingEqual_SequentialCodingTask.runStagePrivately().
{
         if (i < _currentStage && _currentStage != -1)
             throw new IllegalArgumentException(_currentStage + " vs. " + i);
         _currentStage = i;
         _stageTimes[_currentStage + 1] = System.nanoTime();
     }