raccoon: org.msrg.raccoon.engine.task.sequential.SequentialCodingTask.runInitialSequencialTasks
runInitialSequencialTasks()
synchronized final void org.msrg.raccoon.engine.task.sequential.SequentialCodingTask.runInitialSequencialTasks ()
Definition at line 38 of file SequentialCodingTask.java.
References org.msrg.raccoon.engine.task.sequential.SequentialCodingTask.codingFailed(), org.msrg.raccoon.engine.task.sequential.SequentialCodingTask.codingFinished(), org.msrg.raccoon.engine.task.sequential.SequentialCodingTask.codingStarted(), org.msrg.raccoon.engine.task.sequential.SequentialCodingTask.finished(), org.msrg.raccoon.engine.task.sequential.SequentialCodingTask.reachedFinalStage(), and org.msrg.raccoon.engine.task.sequential.SequentialCodingTask.runStagePrivately().
Referenced by org.msrg.raccoon.engine.thread.CodingThreadImpl.runTask().
{
         if (_currentStage != -1)
             throw new IllegalStateException("Expected: " + -1 + ", found: " + _currentStage);
         runStagePrivately();
         if (reachedFinalStage())
             finished();
     }