raccoon: org.msrg.raccoon.engine.task.sequential.SequentialCodingTask.reachedFinalStage
final boolean org.msrg.raccoon.engine.task.sequential.SequentialCodingTask.reachedFinalStage () protected
Definition at line 60 of file SequentialCodingTask.java.
References org.msrg.raccoon.engine.task.sequential.SequentialCodingTask.getFinalStage().
Referenced by org.msrg.raccoon.engine.task.sequential.MultiplyInverseMultiplyEqual_SequentialCodingTask.codingFinished(), org.msrg.raccoon.engine.task.sequential.BulkMatrixEqual_CodingTask.codingFinished(), org.msrg.raccoon.engine.task.sequential.Decoding_SequentialCodingTask.codingFinished(), org.msrg.raccoon.engine.task.sequential.MultiplyBulkMatrix_SequentialCodingTask.codingFinished(), org.msrg.raccoon.engine.task.sequential.EncodingDecodingEqual_SequentialCodingTask.codingFinished(), org.msrg.raccoon.engine.task.sequential.Encoding_SequentialCodingTask.codingFinished(), org.msrg.raccoon.engine.task.sequential.SequentialCodingTask.runInitialSequencialTasks(), and org.msrg.raccoon.engine.task.sequential.EncodingReceivedEncodingDecodingEqual_SequentialCodingTask.runStagePrivately().
{
         return (_currentStage >= getFinalStage());
     }