raccoon: org.msrg.raccoon.CodedBatch.getCodedBatchType
getCodedBatchType()
final CodedBatchType org.msrg.raccoon.CodedBatch.getCodedBatchType ()
Implements org.msrg.raccoon.ICodedBatch.
Definition at line 128 of file CodedBatch.java.
References org.msrg.raccoon.CodedBatch._codedBatchType.
Referenced by org.msrg.raccoon.engine.task.sequential.Encoding_SequentialCodingTask.Encoding_SequentialCodingTask(), org.msrg.raccoon.engine.task.sequential.Encoding_SequentialCodingTask.getEncoding_SequentialCodingTask(), and org.msrg.raccoon.CodedBatch.toString().
{
         return _codedBatchType;
     }