raccoon: org.msrg.raccoon.CodedBatch.getBulkMatrix
BulkMatrix org.msrg.raccoon.CodedBatch.getBulkMatrix ()
Implements org.msrg.raccoon.ICodedBatch.
Definition at line 99 of file CodedBatch.java.
References org.msrg.raccoon.CodedBatch._bm, and org.msrg.raccoon.CodedBatch._lock.
Referenced by org.msrg.raccoon.engine.task.sequential.EncodingDecodingEqual_SequentialCodingTask.EncodingDecodingEqual_SequentialCodingTask(), org.msrg.raccoon.engine.task.sequential.EncodingSourceCodedBatch_SequentialCodingTask.runStagePrivately(), org.msrg.raccoon.engine.task.sequential.EncodingDecodingEqual_SequentialCodingTask.runStagePrivately(), org.msrg.raccoon.engine.task.sequential.EncodingReceivedEncodingDecodingEqual_SequentialCodingTask.runStagePrivately(), org.msrg.raccoon.CodedBatchTest.setUp(), org.msrg.raccoon.SlicedCodedBatchTest.setUp(), and org.msrg.raccoon.ReceivedCodedBatchTest.ttestEncodingDecodingReceivedCodedBatch().
{
         synchronized (_lock) {
             return _bm;
         }
     }