raccoon: org.msrg.raccoon.ReceivedCodedBatchTest.ttestEncodingDecodingReceivedCodedBatch
ttestEncodingDecodingReceivedCodedBatch()
void org.msrg.raccoon.ReceivedCodedBatchTest.ttestEncodingDecodingReceivedCodedBatch ()
Definition at line 29 of file ReceivedCodedBatchTest.java.
References org.msrg.raccoon.ReceivedCodedBatchTest._rows, org.msrg.raccoon.ReceivedCodedBatch.addCodedSlice(), org.msrg.raccoon.ReceivedCodedBatch.canSolve(), org.msrg.raccoon.ReceivedCodedBatch.decode(), org.msrg.raccoon.matrix.bulk.BulkMatrix.equals(), org.msrg.raccoon.ReceivedCodedBatch.getAvailableCodedPieceCount(), org.msrg.raccoon.CodedBatch.getBulkMatrix(), org.msrg.raccoon.ReceivedCodedBatch.getRequiredCodedPieceCount(), and org.msrg.raccoon.CodedPiece.makeCodedPiece().
{
         System.out.print("Creating coded pieces [" + _rcb.getRequiredCodedPieceCount() + "]...");
         long start = System.currentTimeMillis();
         CodedPiece[] cp = new CodedPiece[_rows];
         for (int i = 0; i < _rcb.getRequiredCodedPieceCount(); i++) {
             assertTrue(_rcb.getAvailableCodedPieceCount() == i);
             assertTrue(_rcb.canSolve() == null);
             cp[i] = CodedPiece.makeCodedPiece(_bm);
             _rcb.addCodedSlice(cp[i]);
         }
         long end = System.currentTimeMillis();
         System.out.println(" " + (end - start) + " ms.");
         System.out.print("Decoding...");
         start = System.currentTimeMillis();
         assertTrue(_rcb.decode());
         end = System.currentTimeMillis();
         System.out.println(" " + (end - start) + " ms.");
         System.out.print("Verifying...");
         start = System.currentTimeMillis();
         BulkMatrix decodedBM = _rcb.getBulkMatrix();
         assertTrue(_bm.equals(decodedBM));
         end = System.currentTimeMillis();
         System.out.println(" " + (end - start) + " ms.");
     }