raccoon: org.msrg.raccoon.matrix.finitefields.FFByteMatrix.decloneExtended
FFByteMatrix org.msrg.raccoon.matrix.finitefields.FFByteMatrix.decloneExtended ()
Definition at line 47 of file FFByteMatrix.java.
References org.msrg.raccoon.matrix.TypedMatrix< T >._b, org.msrg.raccoon.matrix.TypedMatrix< T >._cols, org.msrg.raccoon.matrix.TypedMatrix< T >._inverseRowZero, org.msrg.raccoon.matrix.TypedMatrix< T >._rows, org.msrg.raccoon.matrix.finitefields.FFByteMatrix.clone(), org.msrg.raccoon.matrix.finitefields.FFByteMatrix.createNewMatrix(), org.msrg.raccoon.matrix.finitefields.FFByteMatrix.getEmptyArray(), and org.msrg.raccoon.matrix.TypedMatrix< T >.isZero().
{
         int halfCols = _cols / 2;
         Byte[][] b = getEmptyArray(_rows, halfCols);
         for(int i=0 ; i<halfCols ; i++) {
             boolean rowZero = true;
             for(int j=0 ; j<halfCols ; j++) {
                 b[i][j] = clone(_b[i][j + halfCols]);
                 if(!isZero(_b[i][j]))
                     rowZero = false;
             }
             if(rowZero) {
                 _inverseRowZero = i;
                 return null;
             }
         }
         return createNewMatrix(b);
     }