raccoon: org.msrg.raccoon.matrix.finitefields.FFByteMatrix.clone
FFByteMatrix org.msrg.raccoon.matrix.finitefields.FFByteMatrix.clone ()
Definition at line 89 of file FFByteMatrix.java.
References org.msrg.raccoon.matrix.TypedMatrix< T >._b, org.msrg.raccoon.matrix.TypedMatrix< T >._cols, org.msrg.raccoon.matrix.TypedMatrix< T >._rows, org.msrg.raccoon.matrix.finitefields.FFByteMatrix.FFByteMatrix(), org.msrg.raccoon.matrix.TypedMatrix< T >.getColumnSize(), and org.msrg.raccoon.matrix.TypedMatrix< T >.getRowSize().
Referenced by org.msrg.raccoon.matrix.finitefields.FFByteMatrix.cloneExtended(), and org.msrg.raccoon.matrix.finitefields.FFByteMatrix.decloneExtended().
{
         Byte[][] b = new Byte[_rows][_cols];
         for(int i=0 ; i<getRowSize() ; i++)
             for(int j=0 ; j<getColumnSize() ; j++)
                 b[i][j] = clone(_b[i][j]);
         return new FFByteMatrix(b);
     }