raccoon: org.msrg.raccoon.matrix.finitefields.FFByteMatrix.FFByteMatrix
org.msrg.raccoon.matrix.finitefields.FFByteMatrix.FFByteMatrix (int cols, int rows)
Definition at line 22 of file FFByteMatrix.java.
References org.msrg.raccoon.matrix.finitefields.FFByteMatrix.makeZero2d().
Referenced by org.msrg.raccoon.matrix.finitefields.FFByteMatrix.clone(), org.msrg.raccoon.matrix.finitefields.FFByteMatrix.createMatrix(), org.msrg.raccoon.matrix.finitefields.FFByteMatrix.createNewMatrix(), org.msrg.raccoon.matrix.finitefields.FFByteMatrix.createRandomByteMatrix(), org.msrg.raccoon.matrix.finitefields.FFByteMatrix.getZeroMatrix(), and org.msrg.raccoon.matrix.finitefields.ByteMatrix.multiply().
{
         this(makeZero2d(cols, rows));
     }