raccoon: org.msrg.raccoon.matrix.finitefields.FFByteMatrix.cloneExtended
cloneExtended()
FFByteMatrix org.msrg.raccoon.matrix.finitefields.FFByteMatrix.cloneExtended ()
Definition at line 105 of file FFByteMatrix.java.
References org.msrg.raccoon.matrix.TypedMatrix< T >._b, org.msrg.raccoon.matrix.TypedMatrix< T >._cols, org.msrg.raccoon.matrix.TypedMatrix< T >._rows, org.msrg.raccoon.matrix.finitefields.FFByteMatrix.clone(), org.msrg.raccoon.matrix.finitefields.FFByteMatrix.createNewMatrix(), org.msrg.raccoon.matrix.TypedMatrix< T >.getColumnSize(), org.msrg.raccoon.matrix.finitefields.FFByteMatrix.getEmptyArray(), org.msrg.raccoon.matrix.finitefields.FFByteMatrix.getOne(), org.msrg.raccoon.matrix.TypedMatrix< T >.getRowSize(), and org.msrg.raccoon.matrix.finitefields.FFByteMatrix.getZero().
{
         Byte[][] b = getEmptyArray(_rows, _cols * 2);
         for (int i = 0; i < getRowSize(); i++) {
             for (int j = 0; j < getColumnSize(); j++)
                 b[i][j] = clone(_b[i][j]);
             for (int j = 0; j < getColumnSize(); j++)
                 b[i][j + _cols] = j == i ? getOne() : getZero();
         }
         return createNewMatrix(b);
     }