raccoon: org.msrg.raccoon.engine.task.sequential.EncodingSourceCodedBatch_SequentialCodingTask.runStagePrivately
synchronized void org.msrg.raccoon.engine.task.sequential.EncodingSourceCodedBatch_SequentialCodingTask.runStagePrivately () protected
Definition at line 42 of file EncodingSourceCodedBatch_SequentialCodingTask.java.
References org.msrg.raccoon.engine.task.sequential.Encoding_SequentialCodingTask._codeBatch, org.msrg.raccoon.engine.task.sequential.SequentialCodingTask._currentStage, org.msrg.raccoon.engine.task.sequential.SequentialCodingTask._engine, org.msrg.raccoon.engine.task.CodingTask._result, org.msrg.raccoon.matrix.bulk.BulkMatrix._rows, org.msrg.raccoon.matrix.bulk.SliceMatrix.createEmptyCodedPiece(), org.msrg.raccoon.engine.task.sequential.SequentialCodingTask.failed(), org.msrg.raccoon.CodedBatch.getBulkMatrix(), org.msrg.raccoon.CodedBatch.getNewCodedCoefficients(), org.msrg.raccoon.engine.task.result.SliceMatrix_CodingResult.getResult(), org.msrg.raccoon.engine.task.result.CodingResult.isFailed(), org.msrg.raccoon.engine.task.result.CodingResult.isFinished(), org.msrg.raccoon.engine.ICodingEngine.multiply(), org.msrg.raccoon.engine.task.sequential.SequentialCodingTask.setCurrentStage(), and org.msrg.raccoon.matrix.TypedMatrix< T >.verify().
{
         switch (_currentStage) {
         case -1:
         {
             _cc =
                 _codeBatch.getNewCodedCoefficients(_codeBatch.getBulkMatrix()._rows);
             _cc.verify();
             BulkMatrix bm = _codeBatch.getBulkMatrix();
             _smCodingResult = _engine.multiply(this, _cc, bm);
             setCurrentStage(0);
             break;
         }
         case 0:
         {
             if(_smCodingResult.isFailed()) {
                 failed();
             } else if (_smCodingResult.isFinished()) {
                 SliceMatrix sm = _smCodingResult.getResult();
                 CodedPiece codedSlice = sm.createEmptyCodedPiece(_cc, sm);
                 ((CodedSlice_CodingResult)_result).setResult(codedSlice);
                 setCurrentStage(1);
             }
             break;
         }
         default:
             throw new IllegalStateException("" + _currentStage);
         }
     }