raccoon: org.msrg.raccoon.matrix.bulk.BulkMatrix.createBulkMatixIncrementalData
createBulkMatixIncrementalData()
static BulkMatrix org.msrg.raccoon.matrix.bulk.BulkMatrix.createBulkMatixIncrementalData (int rows, int cols) static
Definition at line 77 of file BulkMatrix.java.
References org.msrg.raccoon.matrix.bulk.SliceMatrix._cols, org.msrg.raccoon.matrix.bulk.BulkMatrix.BulkMatrix(), org.msrg.raccoon.matrix.bulk.BulkMatrix.getSliceCount(), org.msrg.raccoon.matrix.bulk.SliceMatrix.loadNoCopy(), and org.msrg.raccoon.matrix.bulk.BulkMatrix.slice().
Referenced by org.msrg.raccoon.CodedPieceTest.setUp(), org.msrg.raccoon.ReceivedCodedBatchTest.setUp(), org.msrg.raccoon.engine.CodingEngineTest.setUp(), and org.msrg.raccoon.matrix.finitefields.ByteMatrixTest.testMtimesBMtimesInvMIsBM().
{
         BulkMatrix bm = new BulkMatrix(rows, cols);
         int val = 0;
         for (int j = 0; j < bm.getSliceCount(); j++) {
             SliceMatrix slice = bm.slice(j);
             byte[] b = new byte[slice._cols];
             for (int k = 0; k < slice._cols; k++)
                 b[k] = (byte) val++;
             slice.loadNoCopy(b);
         }
         return bm;
     }