raccoon: org.msrg.raccoon.matrix.bulk.BulkMatrix.getContent
getContent()
byte [][] org.msrg.raccoon.matrix.bulk.BulkMatrix.getContent ()
Definition at line 204 of file BulkMatrix.java.
References org.msrg.raccoon.matrix.bulk.BulkMatrix._rows.
Referenced by org.msrg.raccoon.matrix.bulk.BulkMatrix1D.createBulkMatixIncrementalData(), org.msrg.raccoon.matrix.finitefields.ByteMatrix.multiply(), and org.msrg.raccoon.matrix.finitefields.ByteMatrix1D.multiply1D().
{
         byte[][] content = new byte[_rows][];
         for (int i = 0; i < _slices.length; i++)
             content[i] = _slices[i].getContent();
         return content;
     }