raccoon: org.msrg.raccoon.matrix.bulk.BulkMatrix.equals
equals()
boolean org.msrg.raccoon.matrix.bulk.BulkMatrix.equals (Object obj)
Definition at line 108 of file BulkMatrix.java.
References org.msrg.raccoon.matrix.bulk.BulkMatrix._slices, org.msrg.raccoon.matrix.bulk.BulkMatrix.BulkMatrix(), and org.msrg.raccoon.matrix.bulk.BulkMatrix.getSliceCount().
Referenced by org.msrg.raccoon.CodedBatch.equalsExact(), org.msrg.raccoon.engine.CodingEngineTest.processFinishedResult(), org.msrg.raccoon.matrix.finitefields.ByteMatrixTest.testMtimesBMtimesInvMIsBM(), and org.msrg.raccoon.ReceivedCodedBatchTest.ttestEncodingDecodingReceivedCodedBatch().
{
         if (obj == null)
             return false;
         if (!getClass().isAssignableFrom(obj.getClass()))
             return false;
         BulkMatrix smObj = (BulkMatrix) obj;
         int sliceCount = getSliceCount();
         if (sliceCount != smObj.getSliceCount())
             return false;
         for (int i = 0; i < sliceCount; i++)
             if (_slices[i] != null) {
                 if (!_slices[i].equals(smObj._slices[i]))
                     return false;
             } else if (smObj._slices[i] != null)
                 return false;
         return true;
     }