raccoon: org.msrg.raccoon.engine.ICodingEngine.encode
CodedSlice_CodingResult org.msrg.raccoon.engine.ICodingEngine.encode (ICodingListener listener, CodedBatch codeBatch)
Implemented in org.msrg.raccoon.engine.CodingEngineImpl.
Referenced by org.msrg.raccoon.engine.task.sequential.EncodingReceivedEncodingDecodingEqual_SequentialCodingTask.codingFinished(), org.msrg.raccoon.engine.task.sequential.EncodingDecodingEqual_SequentialCodingTask.runStagePrivately(), and org.msrg.raccoon.engine.task.sequential.EncodingReceivedEncodingDecodingEqual_SequentialCodingTask.runStagePrivately().