raccoon: org.msrg.raccoon.ReceivedCodedBatch.decode
boolean org.msrg.raccoon.ReceivedCodedBatch.decode ()
Implements org.msrg.raccoon.ICodedBatch.
Definition at line 156 of file ReceivedCodedBatch.java.
References org.msrg.raccoon.CodedPiece._cc, org.msrg.raccoon.CodedPiece._codedContent, org.msrg.raccoon.ReceivedCodedBatch._inverse, org.msrg.raccoon.CodedBatch._lock, org.msrg.raccoon.ReceivedCodedBatch.canSolve(), org.msrg.raccoon.CodedBatch.createNewBulkMatrix(), org.msrg.raccoon.ReceivedCodedBatch.decodeUsing(), org.msrg.raccoon.CodedCoefficients.getCoefficients(), and org.msrg.raccoon.matrix.TypedMatrix< T >.inverseMatrix().
Referenced by org.msrg.raccoon.CodedBatchTest.testReceivedCodedBatch(), org.msrg.raccoon.SlicedCodedBatchTest.testReceivedCodedBatch(), and org.msrg.raccoon.ReceivedCodedBatchTest.ttestEncodingDecodingReceivedCodedBatch().
{
         synchronized (_lock) {
             if(_solvingCodedSlices != null)
                 return true;
         }
         CodedPiece[] solvingCodedSlices = canSolve();
         if(solvingCodedSlices==null)
             return false;
         // Now solve the equations
         int slicesCount = solvingCodedSlices.length;
         Byte[][] coefficientsArray = new Byte[slicesCount][];
         SliceMatrix[] slicesContent = new SliceMatrix[slicesCount];
         for(int i=0 ; i<slicesCount ; i++) {
             slicesContent[i] = solvingCodedSlices[i]._codedContent;
             coefficientsArray[i] = solvingCodedSlices[i]._cc.getCoefficients();
         }
         BulkMatrix contentMatrix = createNewBulkMatrix(slicesContent);
         ByteMatrix coefficientsMatrix = new ByteMatrix(coefficientsArray);
         ByteMatrix coefficientsMatrixInverse = (ByteMatrix) coefficientsMatrix.inverseMatrix();
         if(coefficientsMatrixInverse == null)
             return false;
         coefficientsMatrixInverse = _inverse;
         return decodeUsing(coefficientsMatrixInverse, contentMatrix);
     }