raccoon: org.msrg.raccoon.ReceivedCodedBatch.canSolveHighPriority
canSolveHighPriority()
CodedPiece [] org.msrg.raccoon.ReceivedCodedBatch.canSolveHighPriority () protected
Definition at line 99 of file ReceivedCodedBatch.java.
References org.msrg.raccoon.ReceivedCodedBatch._solvingCodedSlices, org.msrg.raccoon.matrix.TypedMatrix< T >.getInverseRowZero(), org.msrg.raccoon.ReceivedCodedBatch.getRandomIndex(), org.msrg.raccoon.ReceivedCodedBatch.getRequiredCodedPieceCount(), org.msrg.raccoon.matrix.TypedMatrix< T >.inverseMatrix(), org.msrg.raccoon.matrix.finitefields.ByteMatrix.isInversable(), and org.msrg.raccoon.ReceivedCodedBatch.removeBadRow().
Referenced by org.msrg.raccoon.ReceivedCodedBatch.canSolve().
{
         int requiredSlices = getRequiredCodedPieceCount();
         ByteMatrix ncm = null;
         List<Integer> indexSet = getRandomIndex(_cbbs.size(), requiredSlices);
         Byte[][] coefs = new Byte[requiredSlices][];
         int i = 0;
         for (Integer j : indexSet)
             coefs[i++] = _cbbs.get(j)._cc.getCoefficients();
         ncm = new ByteMatrix(coefs);
         if (!ncm.isInversable()) {
             int badRow = ncm.getInverseRowZero();
             removeBadRow(badRow);
             return null;
         }
         _solvingCodedSlices = new CodedPiece[indexSet.size()];
         i = 0;
         for (Integer index : indexSet)
             _solvingCodedSlices[i++] = _cbbs.get(index.intValue());
         _inverse = (ByteMatrix) ncm.inverseMatrix();
         return _solvingCodedSlices;
 //      Combinations combinations = Combinations.makeAllCombinations(requiredSlices, receivedSlices);
 //      BitSet[] bvs = combinations.getAllCombinations();
 //      for(BitSet bv : bvs) {
 //          Byte[][] coefs = getCoefficients(bv, requiredSlices);
 //          ByteMatrix ncm = new ByteMatrix(coefs);
 //          if(ncm.isInversable()) {
 //              solvingCodedSlices = getCodedSlices(bv, requiredSlices);
 //              break;
 //          }
 //      }
     }