raccoon: org.msrg.raccoon.engine.CodingEngineImpl.encode
encode()
CodedSlice_CodingResult org.msrg.raccoon.engine.CodingEngineImpl.encode (ICodingListener listener, CodedBatch codeBatch)
Implements org.msrg.raccoon.engine.ICodingEngine.
Definition at line 218 of file CodingEngineImpl.java.
References org.msrg.raccoon.engine.task.CodingTask._result, org.msrg.raccoon.engine.CodingEngine.addCodingTaskEngineEvent(), org.msrg.raccoon.engine.task.sequential.Encoding_SequentialCodingTask.getEncoding_SequentialCodingTask(), and org.msrg.raccoon.engine.task.CodingId.getNewCodingId().
{
         CodingId id = CodingId.getNewCodingId();
         CodingTask cTask =
                 Encoding_SequentialCodingTask.getEncoding_SequentialCodingTask(this, listener, id, codeBatch);
         CodingEngineEvent_NewCodingTask newCodingEvent = new CodingEngineEvent_NewCodingTask(cTask);
         addCodingTaskEngineEvent(newCodingEvent);
         return (CodedSlice_CodingResult) cTask._result;
     }