raccoon: org.msrg.raccoon.engine.CodingEngineImpl.processCodingEvent
processCodingEvent()
void org.msrg.raccoon.engine.CodingEngineImpl.processCodingEvent (CodingEngineEvent event) protected
Definition at line 130 of file CodingEngineImpl.java.
References org.msrg.raccoon.engine.CodingEngineEvent_NewCodingTask._cTask, org.msrg.raccoon.engine.CodingEngineEvent_ExecutionEvent._cTask, org.msrg.raccoon.engine.CodingEngineEvent_ThreadEvent._cThread, org.msrg.raccoon.engine.CodingEngineEvent._eventType, org.msrg.raccoon.engine.task.CodingTask._listener, org.msrg.raccoon.engine.task.CodingTask._result, org.msrg.raccoon.engine.CodingEngineEvent_SequentialCodingTaskEvents._seqCodingTask, org.msrg.raccoon.engine.ICodingListener.codingFailed(), org.msrg.raccoon.engine.ICodingListener.codingFinished(), org.msrg.raccoon.engine.ICodingListener.codingStarted(), org.msrg.raccoon.engine.task.CodingTaskStatus.FAILED, org.msrg.raccoon.engine.task.CodingTaskStatus.FINISHED, org.msrg.raccoon.engine.task.CodingTask.getStatus(), org.msrg.raccoon.engine.CodingEngine.notifyListener(), org.msrg.raccoon.engine.CodingEngine.scheduleTask(), org.msrg.raccoon.engine.CodingEngineImpl.threadAdded(), org.msrg.raccoon.engine.CodingEngineImpl.threadBecameBusy(), and org.msrg.raccoon.engine.CodingEngineImpl.threadBecameFree().
{
         super.processCodingEvent(event);
         switch (event._eventType) {
             case ENG_ET_NEW_TASK: {
                 CodingEngineEvent_NewCodingTask codingEvent = (CodingEngineEvent_NewCodingTask) event;
                 CodingTask cTask = codingEvent._cTask;
                 scheduleTask(cTask);
                 break;
             }
             case ENG_ET_TASK_FAILED: {
                 CodingEngineEvent_ExecutionEvent execEvent = (CodingEngineEvent_ExecutionEvent) event;
                 CodingTask cTask = execEvent._cTask;
                 CodingTaskStatus status = cTask.getStatus();
                 assert status == CodingTaskStatus.FAILED;
                 ICodingListener listener = cTask._listener;
                 listener.codingFailed(cTask._result);
                 break;
             }
             case ENG_ET_TASK_FINISHED: {
                 CodingEngineEvent_ExecutionEvent execEvent = (CodingEngineEvent_ExecutionEvent) event;
                 CodingTask cTask = execEvent._cTask;
                 CodingTaskStatus status = cTask.getStatus();
                 assert status == CodingTaskStatus.FINISHED;
                 ICodingListener listener = cTask._listener;
                 listener.codingFinished(cTask._result);
                 break;
             }
             case ENG_ET_TASK_STARTED:
                 CodingEngineEvent_ExecutionEvent execEvent = (CodingEngineEvent_ExecutionEvent) event;
                 CodingTask cTask = execEvent._cTask;
                 ICodingListener listener = cTask._listener;
                 listener.codingStarted(cTask._result);
                 break;
             case ENG_ET_THREAD_NEW: {
                 CodingEngineEvent_NewThreadEvent tEvent = (CodingEngineEvent_NewThreadEvent) event;
                 CodingThread cThread = tEvent._cThread;
                 threadAdded(cThread);
                 break;
             }
             case ENG_ET_THREAD_FREE: {
                 CodingEngineEvent_FreeThreadEvent tEvent = (CodingEngineEvent_FreeThreadEvent) event;
                 CodingThread cThread = tEvent._cThread;
                 threadBecameFree(cThread);
                 break;
             }
             case ENG_ET_THREAD_BUSY:
                 CodingEngineEvent_BusyThreadEvent tEvent = (CodingEngineEvent_BusyThreadEvent) event;
                 CodingThread cThread = tEvent._cThread;
                 threadBecameBusy(cThread);
                 break;
             case END_ET_SEQ_TASK_FAILED: {
                 CodingEngineEvent_SequentialCodingTaskFailed seqEvent = (CodingEngineEvent_SequentialCodingTaskFailed) event;
                 SequentialCodingTask seqCodingTask = seqEvent._seqCodingTask;
                 notifyListener(seqCodingTask);
                 break;
             }
             case END_ET_SEQ_TASK_FINISHED:
                 CodingEngineEvent_SequentialCodingTaskFinished seqEvent = (CodingEngineEvent_SequentialCodingTaskFinished) event;
                 SequentialCodingTask seqCodingTask = seqEvent._seqCodingTask;
                 notifyListener(seqCodingTask);
                 break;
             default:
                 throw new UnsupportedOperationException("Unknown event type: " + event);
         }
     }