raccoon: org.msrg.raccoon.matrix.finitefields.ByteMatrix.unwrap
unwrap()
static byte [][] org.msrg.raccoon.matrix.finitefields.ByteMatrix.unwrap (Byte B[][]) static
Definition at line 59 of file ByteMatrix.java.
Referenced by org.msrg.raccoon.matrix.finitefields.ByteMatrix.getByteArray(), org.msrg.raccoon.matrix.finitefields.ByteMatrix.multiply(), and org.msrg.raccoon.matrix.finitefields.ByteMatrixTest.runTestM2timesInvIsM().
{
         byte[][] b = new byte[B.length][];
         for (int i = 0; i < B.length; i++) {
             int rowLen = B[i].length;
             b[i] = new byte[rowLen];
             for (int j = 0; j < rowLen; j++) {
                 b[i][j] = B[i][j];
             }
         }
         return b;
     }