raccoon: org.msrg.raccoon.matrix.finitefields.ByteMatrix.multiply
BulkMatrix org.msrg.raccoon.matrix.finitefields.ByteMatrix.multiply (BulkMatrix bm)
Definition at line 102 of file ByteMatrix.java.
References org.msrg.raccoon.matrix.TypedMatrix< T >._b, org.msrg.raccoon.matrix.TypedMatrix< T >._cols, org.msrg.raccoon.matrix.bulk.BulkMatrix._cols, org.msrg.raccoon.matrix.TypedMatrix< T >._rows, org.msrg.raccoon.matrix.bulk.BulkMatrix._rows, org.msrg.raccoon.matrix.finitefields.FFByteMatrix._tables, org.msrg.raccoon.matrix.bulk.BulkMatrix.createEmptyMatrix(), org.msrg.raccoon.finitefields.Tables.EXP, org.msrg.raccoon.matrix.bulk.BulkMatrix.getContent(), org.msrg.raccoon.matrix.bulk.SliceMatrix.loadNoCopy(), org.msrg.raccoon.finitefields.Tables.LOG, and org.msrg.raccoon.matrix.bulk.BulkMatrix.slice().
Referenced by org.msrg.raccoon.CodedPiece.CodedPiece(), org.msrg.raccoon.ReceivedCodedBatch.decodeUsing(), org.msrg.raccoon.matrix.finitefields.ByteMatrix.multiply(), org.msrg.raccoon.engine.task.sequential.EncodingReceivedCodedBatch_SequentialCodingTask.runStagePrivately(), org.msrg.raccoon.matrix.finitefields.ByteMatrixTest.runTestM2timesInvIsM(), and org.msrg.raccoon.matrix.finitefields.ByteMatrixTest.testMtimesBMtimesInvMIsBM().
{
         if(_cols != bm._rows)
             throw new IllegalArgumentException("Mismatch: " + _cols + " vs. " + bm._rows);
         byte[][] bIn = bm.getContent();
         BulkMatrix outM = bm.createEmptyMatrix(_rows, bm._cols);
         for(int i=0 ; i<_rows ; i++){
             byte[] bRow = new byte[bm._cols];
             for(int j=0 ; j<bm._cols ; j++) {
                 for(int k=0 ; k<_cols ; k++) {
                     byte a = _b[i][k];
                     byte b = bIn[k][j];
 //                  byte mult = _tables.FFMulFast(a, b);
                     byte mult;
                     if(a==0||b==0) {
                         mult = 0;
                     } else {
                        int t = ((_tables.LOG[(a & 0xff)] & 0xff) + (_tables.LOG[(b & 0xff)] & 0xff));
                        mult = _tables.EXP[((t>255)?t-255:t) & 0xff];
                     }
                     bRow[j] ^= (byte)(mult);
                 }
             }
             outM.slice(i).loadNoCopy(bRow);
         }
         return outM;
     }