raccoon: org.msrg.raccoon.engine.task.result.CodingResult.isFailed
isFailed()
boolean org.msrg.raccoon.engine.task.result.CodingResult.isFailed ()
Definition at line 48 of file CodingResult.java.
References org.msrg.raccoon.engine.task.CodingTaskStatus.FAILED.
Referenced by org.msrg.raccoon.engine.CodingEngineTest.codingFailed(), org.msrg.raccoon.engine.task.sequential.EncodingReceivedCodedBatch_SequentialCodingTask.runStagePrivately(), org.msrg.raccoon.engine.task.sequential.EncodingSourceCodedBatch_SequentialCodingTask.runStagePrivately(), org.msrg.raccoon.engine.task.sequential.MultiplyInverseMultiplyEqual_SequentialCodingTask.runStagePrivately(), org.msrg.raccoon.engine.task.sequential.Decoding_SequentialCodingTask.runStagePrivately(), org.msrg.raccoon.engine.task.sequential.EncodingDecodingEqual_SequentialCodingTask.runStagePrivately(), org.msrg.raccoon.engine.task.result.Equals_CodingResult.setResult(), org.msrg.raccoon.engine.task.result.BulkMatrix_CodingResult.setResult(), org.msrg.raccoon.engine.task.result.ByteMatrix_CodingResult.setResult(), org.msrg.raccoon.engine.task.result.CodedSlice_CodingResult.setResult(), and org.msrg.raccoon.engine.task.result.SliceMatrix_CodingResult.setResult().
{
         return _status == CodingTaskStatus.FAILED;
     }