raccoon: org.msrg.raccoon.engine.task.sequential.EncodingDecodingEqual_SequentialCodingTask.EncodingDecodingEqual_SequentialCodingTask
org.msrg.raccoon.engine.task.sequential.EncodingDecodingEqual_SequentialCodingTask.EncodingDecodingEqual_SequentialCodingTask (CodedBatch codedBatch, ICodingEngine engine, ICodingListener listener, CodingId id)
Definition at line 38 of file EncodingDecodingEqual_SequentialCodingTask.java.
References org.msrg.raccoon.matrix.bulk.BulkMatrix._rows, org.msrg.raccoon.engine.task.sequential.SequentialCodingTaskType.ENCODE_DECODE_EQUAL, org.msrg.raccoon.CodedBatch.getBulkMatrix(), org.msrg.raccoon.CodedBatch.getSize(), and org.msrg.raccoon.engine.task.sequential.SequentialCodingTask.setCurrentStage().
{
         super(engine, listener, id, SequentialCodingTaskType.ENCODE_DECODE_EQUAL);
         _codedBatch = codedBatch;
         _receiverCodedBatch = new ReceivedCodedBatch(_codedBatch.getSize(), _codedBatch.getBulkMatrix()._rows);
         setCurrentStage(-1);
     }