raccoon: org.msrg.raccoon.engine.task.sequential.EncodingDecodingEqual_SequentialCodingTask.runStagePrivately
void org.msrg.raccoon.engine.task.sequential.EncodingDecodingEqual_SequentialCodingTask.runStagePrivately () protected
Definition at line 86 of file EncodingDecodingEqual_SequentialCodingTask.java.
References org.msrg.raccoon.engine.task.sequential.SequentialCodingTask._currentStage, org.msrg.raccoon.engine.task.sequential.SequentialCodingTask._engine, org.msrg.raccoon.engine.task.CodingTask._result, org.msrg.raccoon.engine.task.CodingTask._status, org.msrg.raccoon.ReceivedCodedBatch.addCodedSlice(), org.msrg.raccoon.engine.ICodingEngine.checkEquality(), org.msrg.raccoon.engine.ICodingEngine.decode(), org.msrg.raccoon.engine.ICodingEngine.encode(), org.msrg.raccoon.engine.task.sequential.SequentialCodingTask.failed(), org.msrg.raccoon.CodedBatch.getAvailableCodedPieceCount(), org.msrg.raccoon.CodedBatch.getBulkMatrix(), org.msrg.raccoon.engine.task.result.Equals_CodingResult.getResult(), org.msrg.raccoon.engine.task.result.CodingResult.isFailed(), org.msrg.raccoon.engine.task.CodingTask.isFailed(), org.msrg.raccoon.engine.task.result.CodingResult.isFinished(), and org.msrg.raccoon.engine.task.sequential.SequentialCodingTask.setCurrentStage().
Referenced by org.msrg.raccoon.engine.task.sequential.EncodingDecodingEqual_SequentialCodingTask.codingFinished().
{
         if(isFailed())
             return;
         switch (_currentStage) {
         case -1:
         {
             int requiredSlices = _codedBatch.getAvailableCodedPieceCount();
             _encodingResults = new CodedSlice_CodingResult[requiredSlices];
             _encodintResultsSet = new HashSet<CodedSlice_CodingResult>();
             for(int i=0 ; i<requiredSlices ; i++) {
                 CodedSlice_CodingResult encodingResult = _engine.encode(this, _codedBatch);
                 _encodingResults[i] = encodingResult;
                 _encodintResultsSet.add(encodingResult);
             }
             setCurrentStage(0);
             break;
         }
         case 0:
         {
             if(_encodintResultsSet.isEmpty()) {
                 for(CodedSlice_CodingResult codedResult : _encodingResults) {
                     if(!codedResult.isFinished()) {
                         throw new IllegalStateException();
                     } else {
                         CodedPiece cSlice = codedResult.getResult();
                         _receiverCodedBatch.addCodedSlice(cSlice);
                     }
                 }
                 _decodingResults = _engine.decode(this, _receiverCodedBatch);
                 setCurrentStage(1);
             }
             break;
         }
         case 1:
         {
             if(_decodingResults.isFailed())
                 failed();
             else if(_decodingResults.isFinished()) {
                 if (!_decodingResults.getResult()) {
                     ((Equals_CodingResult)_result).setResult(false);
                     setCurrentStage(2);
                     setCurrentStage(3);
                     setCurrentStage(4);
                     setCurrentStage(5);
                 } else {
                     BulkMatrix bm1 = _codedBatch.getBulkMatrix();
                     BulkMatrix bm2 = _receiverCodedBatch.getBulkMatrix();
                     if(bm2==null) {
                         ((Equals_CodingResult)_result).setResult(false);
                         setCurrentStage(2);
                         setCurrentStage(3);
                         setCurrentStage(4);
                     } else {
                         _decodedEqualityResult = _engine.checkEquality(this, bm1, bm2);
                         setCurrentStage(2);
                     }
                 }
             }
             break;
         }
         case 2:
         {
             if(_decodedEqualityResult.isFailed()) {
                 failed();
             }else if(_decodedEqualityResult.isFinished()) {
                 boolean result = _decodedEqualityResult.getResult();
                 ((Equals_CodingResult)_result).setResult(result);
                 setCurrentStage(3);
             }
             break;
         }
         default:
             throw new IllegalStateException("" + _currentStage + ":" + _status);
         }
     }