raccoon: org.msrg.raccoon.matrix.finitefields.ByteMatrixTest.testMtimesBMtimesInvMIsBM
testMtimesBMtimesInvMIsBM()
void org.msrg.raccoon.matrix.finitefields.ByteMatrixTest.testMtimesBMtimesInvMIsBM ()
Definition at line 119 of file ByteMatrixTest.java.
References org.msrg.raccoon.matrix.finitefields.ByteMatrixTest.BYTE_MATRIX_SIZE, org.msrg.raccoon.matrix.bulk.BulkMatrix.createBulkMatixIncrementalData(), org.msrg.raccoon.matrix.finitefields.ByteMatrix.createRandomByteMatrix(), org.msrg.raccoon.matrix.bulk.BulkMatrix.equals(), org.msrg.raccoon.matrix.TypedMatrix< T >.getColumnSize(), org.msrg.raccoon.matrix.TypedMatrix< T >.getRowSize(), org.msrg.raccoon.matrix.TypedMatrix< T >.inverseMatrix(), and org.msrg.raccoon.matrix.finitefields.ByteMatrix.multiply().
{
         System.out.println("******* " + "testMtimesBMtimesInvMIsBM");
         long start = System.currentTimeMillis();
         int rows = BYTE_MATRIX_SIZE, cols = BYTE_MATRIX_SIZE;
         System.out.print("Creating [" + rows + "x" + cols + "] ... ");
         long end = System.currentTimeMillis();
         ByteMatrix ncM = ByteMatrix.createRandomByteMatrix(rows, cols);
         System.out.println(" " + (end - start) + " ms.");
         System.out.print("Inversing[" + ncM.getRowSize() + "x" + ncM.getColumnSize() + "... ");
         start = System.currentTimeMillis();
         ByteMatrix ncMInv = (ByteMatrix) ncM.inverseMatrix();
         end = System.currentTimeMillis();
         System.out.println(" " + (end - start) + " ms.");
         System.out.print("Creating Bulk [" + BULK_SIZE + "] ... ");
         start = System.currentTimeMillis();
         BulkMatrix bm =
                 BulkMatrix.createBulkMatixIncrementalData(
                         ncM.getColumnSize(), (int) Math.ceil(BULK_SIZE / ncM.getColumnSize()));
         end = System.currentTimeMillis();
         System.out.println(" " + (end - start) + " ms.");
         System.out.print("Multiplying Bulk... ");
         start = System.currentTimeMillis();
         BulkMatrix ncMTimesBm = ncM.multiply(bm);
         end = System.currentTimeMillis();
         System.out.println(" " + (end - start) + " ms.");
         System.out.print("Multiplying Bulk and Inverse... ");
         start = System.currentTimeMillis();
         BulkMatrix ncMInvTimesncMTimesBm = ncMInv.multiply(ncMTimesBm);
         end = System.currentTimeMillis();
         System.out.println(" " + (end - start) + " ms.");
         System.out.print("Verifying equality... ");
         start = System.currentTimeMillis();
         assertTrue(ncMInvTimesncMTimesBm.equals(bm));
         end = System.currentTimeMillis();
         System.out.println("OK!");
     }