raccoon: org.msrg.raccoon.matrix.finitefields.ByteMatrixTest.runTestManyInverse
runTestManyInverse()
void org.msrg.raccoon.matrix.finitefields.ByteMatrixTest.runTestManyInverse (int rows, int runsPerRows)
Definition at line 107 of file ByteMatrixTest.java.
References org.msrg.raccoon.matrix.finitefields.ByteMatrix.createRandomByteMatrix(), org.msrg.raccoon.matrix.TypedMatrix< T >.getColumnSize(), org.msrg.raccoon.matrix.TypedMatrix< T >.getRowSize(), and org.msrg.raccoon.matrix.TypedMatrix< T >.inverseMatrix().
Referenced by org.msrg.raccoon.matrix.finitefields.ByteMatrixTest.testManyInverse().
{
         for (int i = 0; i < runsPerRows; i++) {
             ByteMatrix ncM = ByteMatrix.createRandomByteMatrix(rows, rows);
             System.out.print("Inversing[" + ncM.getRowSize() + "x" + ncM.getColumnSize() + "]... ");
             double start = System.nanoTime();
             ByteMatrix ncMInv = (ByteMatrix) ncM.inverseMatrix();
             double end = System.nanoTime();
             System.out.println(String.format("%6f ms", (end - start) / 1000000));
             assertNotNull(ncMInv);
         }
     }