raccoon: org.msrg.raccoon.matrix.finitefields.ByteMatrixTest.runTestM2timesInvIsM
void org.msrg.raccoon.matrix.finitefields.ByteMatrixTest.runTestM2timesInvIsM (ByteMatrix ncM, boolean hasInverse) protected
Definition at line 61 of file ByteMatrixTest.java.
References org.msrg.raccoon.matrix.TypedMatrix< T >.equals(), org.msrg.raccoon.matrix.TypedMatrix< T >.getColumnSize(), org.msrg.raccoon.matrix.TypedMatrix< T >.getInverseRowZero(), org.msrg.raccoon.matrix.TypedMatrix< T >.getRowSize(), org.msrg.raccoon.matrix.TypedMatrix< T >.inverseMatrix(), org.msrg.raccoon.matrix.MatrixFactory.multiply(), org.msrg.raccoon.matrix.finitefields.ByteMatrix.multiply(), org.msrg.raccoon.matrix.TypedMatrix< T >.toArray(), org.msrg.raccoon.matrix.finitefields.ByteMatrix.unwrap(), and org.msrg.raccoon.matrix.finitefields.ByteMatrix.wrap().
Referenced by org.msrg.raccoon.matrix.finitefields.ByteMatrixTest.testM2timesInvIsM_HasInvserse(), and org.msrg.raccoon.matrix.finitefields.ByteMatrixTest.testM2timesInvIsM_HasNoInvserse().
{
         System.out.print("Multiplying... ");
         long start = System.currentTimeMillis();
         ByteMatrix ncMP2 = new ByteMatrix(
                     ByteMatrix.wrap(
                             ncM.multiply(ByteMatrix.unwrap(ncM.toArray()))
                     )
                 );
         long end = System.currentTimeMillis();
         System.out.println(" " + (end - start) + " ms.");
         System.out.print("Inversing[" + ncM.getRowSize() + "x" + ncM.getColumnSize() + "... ");
         start = System.currentTimeMillis();
         ByteMatrix ncMInv = (ByteMatrix) ncM.inverseMatrix();
         end = System.currentTimeMillis();
         System.out.println(" " + (end - start) + " ms.");
         int inverseRowZero = ncM.getInverseRowZero();
         if(!hasInverse) {
             assertNull(ncMInv);
             assertTrue(inverseRowZero >= 0);
             assertTrue(inverseRowZero < ncM.getRowSize());
             return;
         }
         assertNotNull(ncMInv);
         assertTrue(inverseRowZero == -1);
         System.out.print("Multiplying... ");
         start = System.currentTimeMillis();
         ByteMatrix ncMInvTimesncMP2 = (ByteMatrix) MatrixFactory.multiply(ncMP2, ncMInv);
         end = System.currentTimeMillis();
         System.out.println(" " + (end - start) + " ms.");
         System.out.print("Verifying... ");
         start = System.currentTimeMillis();
         assertTrue(ncMInvTimesncMP2.equals(ncM));
         end = System.currentTimeMillis();
         System.out.println(" " + (end - start) + " ms.");
         System.out.println("OK!");
     }