raccoon: org.msrg.raccoon.engine.thread.CodingThreadImpl.runTask
runTask()
void org.msrg.raccoon.engine.thread.CodingThreadImpl.runTask (CodingTask codingTask) protected
Definition at line 27 of file CodingThreadImpl.java.
References org.msrg.raccoon.engine.task.Multiply_CodingTask._bm, org.msrg.raccoon.engine.task.Inverse_CodingTask._m, org.msrg.raccoon.engine.task.Multiply_CodingTask._m, org.msrg.raccoon.engine.task.CodingTask._result, org.msrg.raccoon.engine.task.SlicesEqual_CodingTask._sm1, org.msrg.raccoon.engine.task.SlicesEqual_CodingTask._sm2, org.msrg.raccoon.engine.task.CodingTask._taskType, org.msrg.raccoon.matrix.bulk.SliceMatrix.equals(), org.msrg.raccoon.engine.task.CodingTask.failed(), org.msrg.raccoon.engine.task.CodingTask.finished(), org.msrg.raccoon.matrix.TypedMatrix< T >.inverseMatrix(), org.msrg.raccoon.matrix.finitefields.ByteMatrix1D.multiply1D(), and org.msrg.raccoon.engine.task.sequential.SequentialCodingTask.runInitialSequencialTasks().
{
         super.runTask(codingTask);
         CodingTaskType taskType = codingTask._taskType;
         switch (taskType) {
             case SLICES_EQUAL:
                 SlicesEqual_CodingTask smeCodingTask = (SlicesEqual_CodingTask) codingTask;
                 SliceMatrix sm1 = smeCodingTask._sm1;
                 SliceMatrix sm2 = smeCodingTask._sm2;
                 boolean equals = sm1.equals(sm2);
                 ((Equals_CodingResult) smeCodingTask._result).setResult(equals);
                 smeCodingTask.finished();
                 break;
             case INVERSE: {
                 Inverse_CodingTask inverseCodingTask = (Inverse_CodingTask) codingTask;
                 ByteMatrix m = inverseCodingTask._m;
                 ByteMatrix mInverse = (ByteMatrix) m.inverseMatrix();
                 ((ByteMatrix_CodingResult) inverseCodingTask._result).setResult(mInverse);
                 inverseCodingTask.finished();
                 break;
             }
             case MULTIPLY:
                 Multiply_CodingTask multiplyCodingTask = (Multiply_CodingTask) codingTask;
                 ByteMatrix1D m = multiplyCodingTask._m;
                 BulkMatrix bm = multiplyCodingTask._bm;
                 SliceMatrix result = null;
                 try {
                     result = m.multiply1D(bm);
                 } catch (Exception x) {
                     x.printStackTrace();
                     multiplyCodingTask.failed();
                     break;
                 }
                 ((SliceMatrix_CodingResult) multiplyCodingTask._result).setResult(result);
                 multiplyCodingTask.finished();
                 break;
             case SEQUENCIAL:
                 SequentialCodingTask seqCodingTask = (SequentialCodingTask) codingTask;
                 seqCodingTask.runInitialSequencialTasks();
                 break;
             default:
                 throw new UnsupportedOperationException("Unknown task type: " + taskType);
         }
     }